### ISSUE TITLE
Android M cannot create managed profile if device owner exist

### ISSUE THREAD

**Issue by shizhx** [googlesamples/android-testdpc#10]
on Android L, profile owner and device owner must be same component.
but why this strategy changed on Android M?

**Comment by AndrewScull** [comment]
You are seeing the expected behavior with Android M. Are you depending on creating a managed profile when there is already a device owner installed?

**Comment by shizhx** [comment]
@AndrewScull I want to create a managed profile when I am device owner.
in other words, I want to be a device owner and a profile owner at the same time.

PS:
device owner can only manage device, but cannot segregate data, profile owner can do that.

**Comment by ming030890** [comment]
@shizhx Sorry, it is not supported at this moment

**Comment by shizhx** [comment]
@ming030890 it is supported on Android L, but Android M changed.
here is the commit:
https://android.googlesource.com/platform/packages/apps/ManagedProvisioning/+/6079da1206b137da41db49fa7c3bf54f3ce62641

**I want to know the intention of this change.**

**Comment by ming030890** [comment]
It is because we have not well defined the expected behavior of it yet.
We may review this in the future.

Thanks.
