### ISSUE TITLE
TestDpc  Crashed in Android Q

### ISSUE THREAD

**Issue by RanForLei** [googlesamples/android-testdpc#102]
I use the TestDpc on Android Q, and I got a Crash on the version 6.2.0. Please help:

01-10 21:17:02.535 28585 28585 D AndroidRuntime: Shutting down VM
01-10 21:17:02.535 28585 28585 E AndroidRuntime: FATAL EXCEPTION: main
01-10 21:17:02.535 28585 28585 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 28585
01-10 21:17:02.535 28585 28585 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.afwsamples.testdpc/com.afwsamples.testdpc.PolicyManagementActivity}: java.lang.SecurityException: Must have android.permission.GET_AND_REQUEST_SCREEN_LOCK_COMPLEXITY permission.: Neither user 10152 nor current process has android.permission.GET_AND_REQUEST_SCREEN_LOCK_COMPLEXITY.
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:209)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7021)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
01-10 21:17:02.535 28585 28585 E AndroidRuntime: Caused by: java.lang.SecurityException: Must have android.permission.GET_AND_REQUEST_SCREEN_LOCK_COMPLEXITY permission.: Neither user 10152 nor current process has android.permission.GET_AND_REQUEST_SCREEN_LOCK_COMPLEXITY.
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2059)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2027)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1977)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.admin.IDevicePolicyManager$Stub$Proxy.getPasswordComplexity(IDevicePolicyManager.java:7318)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.admin.DevicePolicyManager.getPasswordComplexity(DevicePolicyManager.java:3360)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at com.afwsamples.testdpc.policy.PolicyManagementFragment.loadPasswordComplexity(PolicyManagementFragment.java:2174)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at com.afwsamples.testdpc.policy.PolicyManagementFragment.onResume(PolicyManagementFragment.java:776)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.Fragment.performResume(Fragment.java:2580)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3014)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.FragmentController.dispatchResume(FragmentController.java:206)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:7807)
01-10 21:17:02.535 28585 28585 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3981)

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
