### ISSUE TITLE
Wrong compile version for R

### ISSUE THREAD

**Issue by tir38** [googlesamples/android-testdpc#106]
I know that you [just bumped this to build with android-R like 12 hours ago](https://github.com/googlesamples/android-testdpc/commit/bc742776aff12c50c081bc771e2addef997305d3#diff-39e7d8c00954e920b98e7636f0ac30b2R14), but this looks like it's already changed. I think the finally gave the preview the `30` value. 

https://developer.android.com/preview/setup-sdk#update-build

```
android {
    compileSdkVersion 30

    defaultConfig {
        targetSdkVersion 30
    }
    ...
}
```

I'm trying to build now but can't locate android-R
 
```
> Failed to find Platform SDK with path: platforms;android-R
```

If I set compile and target SDKs to `30` then it builds just fine

FYI you can also remove the `buildTools` line. AGP now sets that automagically

**Comment by jscott1989** [comment]
Thanks for this. I'll push an update for this on Monday.

**Comment by jscott1989** [comment]
Maybe Monday was over-ambitious. I will get to it this week.
