### ISSUE TITLE
Reference Play Store app

### ISSUE THREAD

**Issue by tir38** [googlesamples/android-testdpc#107]
Not sure if this play store app is "official":  https://play.google.com/store/apps/details?id=com.afwsamples.testdpc&hl=en

If it is, will you make reference to it in the README? Since that app is not built and linked to Google's developer account it's not clear if it's official or potentially harmful.

**Comment by jscott1989** [comment]
It is official. I've added it as the "website" on GitHub for now and will add it to the README on the next update.
