### ISSUE TITLE
Android 11: not possible to create managed (work) profile

### ISSUE THREAD

**Issue by test-acc-vaccym** [googlesamples/android-testdpc#108]
When the app is provisioned as the profile owner (or as the device owner), setting up managed (work) profile after that is not possible.

This is the error when clicking on "Set up TestDPC" from launcher or withing the app:

"TestDPC isn't currently allowed to be set up as the profile or device owner"

**Comment by jscott1989** [comment]
This relies on [DevicePolicyManager#isProvisioningAllowed(java.lang.String)](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#isProvisioningAllowed(java.lang.String)) to decide if it can be set up.

Ensure you device is in a state where it can be set as PO/DO and if it's still failing please open a [bug report against Android](https://source.android.com/setup/contribute/report-bugs).
