### ISSUE TITLE
Can't launch TestDPC (7.0.0) activity on Android 9 devices

### ISSUE THREAD

**Issue by SeanTseng1976** [googlesamples/android-testdpc#109]
After using afw#testdpc in SetupWizard to provision TestDPC as DO,  the TestDPC would crashed when it is launched by clicking the testdpc app icon.

--------- beginning of crash
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: FATAL EXCEPTION: main
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 8877
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getAutoTimeEnabled(Landroid/content/ComponentName;)Z in class Landroid/app/admin/DevicePolicyManager; or its super classes (declaration of 'android.app.admin.DevicePolicyManager' appears in /system/framework/framework.jar)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at com.afwsamples.testdpc.policy.PolicyManagementFragment.reloadSetAutoTimeUi(PolicyManagementFragment.java:2536)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at com.afwsamples.testdpc.policy.PolicyManagementFragment.onCreatePreferences(PolicyManagementFragment.java:781)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at androidx.preference.PreferenceFragment.onCreate(PreferenceFragment.java:225)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at com.afwsamples.testdpc.common.BaseSearchablePolicyPreferenceFragment.onCreate(BaseSearchablePolicyPreferenceFragment.java:36)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at com.afwsamples.testdpc.policy.PolicyManagementFragment.onCreate(PolicyManagementFragment.java:523)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2503)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1256)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7151)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6746)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-19 21:22:53.976 10106  8877  8877 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-19 21:22:53.978  1000  2788  5407 W ActivityManager:   Force finishing activity com.afwsamples.testdpc/.PolicyManagementActivity

**Comment by jscott1989** [comment]
Thanks for the report. I'll look into this and get back to you.

**Comment by SunnyBreave** [comment]
@SeanTseng1976 I meet same issue on android 10. I got prop ro.build.version.sdk(29) correct, but it run into API level 30's method -getAutoTimeEnabled

**Comment by jscott1989** [comment]
This should be fixed now in the code. A release onto Github and Play will follow.
