### ISSUE TITLE
setGlobalSetting and setSecureSetting

### ISSUE THREAD

**Issue by luisiwasaki** [googlesamples/android-testdpc#11]
Hi,

Do you have any plans to add full support for **every possible setting** in DPM API's setGlobalSetting and setSecureSetting?

Currently, I can only find implementation for:
-STAY_ON_WHILE_PLUGGED_IN
-WIFI_DEVICE_OWNER_CONFIGS_LOCKDOWN
-INSTALL_NON_MARKET_APPS

Thanks,
Luis.

**Comment by ming030890** [comment]
We don't have such a plan at this moment as we do not want to make these two API to be too powerful.
Also, you may want to check does addUserRestriction fit your use cases.
https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#addUserRestriction(android.content.ComponentName, java.lang.String)
