### ISSUE TITLE
Reg: Accessibility Service for my application installed inside the work profile

### ISSUE THREAD

**Issue by ArunkumarAdhash** [googlesamples/android-testdpc#113]
Hi Developer Team,

I Have tested the Test DPC app to test my application behavior inside the work profile. actually, my application needs Accessibility service.

Steps I followed to enable Accessibility service for my application:

1. I have opened the Test DPC app inside the work profile.
2. when it opened, it shows the policy manager list.
3. I selected the Accessibility - Set Accessibility service option.
4. it lists the apps installed in the personal profile but not in the work profile.

Example:

I have installed the voice access app in both personal and work profile. but when I try to give accessibility service access for voice access apps inside the work profile does not happen. because, the test DPC set accessibility service option only lists the personal profile app not work profile apps.

Excepted Result:

I should able to give accessibility service for apps inside the work profile also. please give your feedback and support on this.

**Comment by rameshwebo** [comment]
Hy developer team !

I faced the same issues  and reported on stackoverflow 
[Work profile from Android management api ](https://stackoverflow.com/questions/64449249/how-to-enable-accessibility-service-in-android-management-api
)

**Comment by jscott1989** [comment]
I see this is answered on stackoverflow
