### ISSUE TITLE
Oops! Couldn't up your device. Contact your IT depertment

### ISSUE THREAD

**Issue by zrklenes** [googlesamples/android-testdpc#114]
Hi;

I am reading the QR code. The app comes to the install screen. It gives such an error.There is only reset button.

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
