### ISSUE TITLE
What does “delegation-package-installation” mean？

### ISSUE THREAD

**Issue by XingHaoxiang** [googlesamples/android-testdpc#116]
I want to ask a question，There is no corresponding Key in DevicePolicyManager，How should i use？

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
