### ISSUE TITLE
Mobile signal lost on OnePlus 7t

### ISSUE THREAD

**Issue by george-kar** [googlesamples/android-testdpc#117]
I have installed TestDPC and created work profile. Everything's fine except a major problem. When I open a GPS application like Google Maps, the mobile signal is drop. Then after a few seconds signal is back, then the 4G is back with a (!) and then 4G is working. This happens every time every day as long as TestDPC is enabled. Uninstalling TestDPC doesnt help. I have to factory reset phone and install everything except for TestDPC. Any idea why?

**Comment by jscott1989** [comment]
There's no reason TestDPC would cause this. If you can demonstrate that it's TestDPC causing this open a new bug.
