### ISSUE TITLE
Disable camera issue

### ISSUE THREAD

**Issue by rajnishvaid12** [googlesamples/android-testdpc#118]
Hi 
I am not able to disable camera on Samsung M30 device . Device support Android 10.
Below steps that i follows to disable camera.
1.First i install Work Profile or Device Profile.
2.Then i disabled camera using profile owner instance with this method getParentProfileInstance().

Thanks in Advance.

**Comment by jscott1989** [comment]
You should raise this with Samsung - assuming it only happens on that device.
