### ISSUE TITLE
Provisioning does not work on either the app store or an apk built from the git repo.

### ISSUE THREAD

**Issue by mddrill** [googlesamples/android-testdpc#119]
Am I doing something wrong? Building from the repo I launched the app on API 24, 28, and 29 and it just says "This app is not an admin with no option to provision. When I download from the app store on API 29, it goes into a provisioning loop where after I add my google account, it just goes to the app store, and when I go back to the provisioning activity it asks if I want to replace my account with a new account. This app seems completely broken.

**Comment by jscott1989** [comment]
If you install the APK, you'll see a "Set up TestDPC" icon on the launcher which will set up a work profile for you. Alternatively you can use an adb command to set TestDPC as the device owner `adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver`
