### ISSUE TITLE
TestDPC isn't currently allowed to create a managed profile on Android 11

### ISSUE THREAD

**Issue by SeanTseng1976** [googlesamples/android-testdpc#120]
After provisioning TestDPC as Device Owner mode in GMS setup wizard on android 11, it seems that TestDPC force to turn on "Disallow add managed profile" and "Disallow add user" in User restrictions settings.

**Comment by SeanTseng1976** [comment]
How to create a sw test environment which fully managed with work profile enabled to test software under this condition?

**Comment by SeanTseng1976** [comment]
[CantCreateManagedProfile.zip](https://github.com/googlesamples/android-testdpc/files/5229315/CantCreateManagedProfile.zip)

**Comment by jindog** [comment]
Dear @SeanTseng1976 , 

I think you need to read this article for Android 11 update w.r.t 'Work Profile on fully managed device', 
https://developer.android.com/work/versions/android-11#work

**Comment by SeanTseng1976** [comment]
Thanks! It's clear to me now!
