### ISSUE TITLE
Notification Disabled

### ISSUE THREAD

**Issue by rameshcool** [googlesamples/android-testdpc#123]
I created a work profile using set up test dpc. After that i installed an app using android studio 4.1. After that load manifest restrictions from managed configurations(Test DPC), tap on save button, but no notification, For any changes in policies notification not working. when i opened app notification panel in settings there missing two categories notification one is mdm_update and other Mobile Device Management service.How to enable it, I'm using android OS 10

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
