### ISSUE TITLE
Can't enroll for Xiaomi Redmi 6 MIUI11

### ISSUE THREAD

**Issue by thinhdd13** [googlesamples/android-testdpc#124]
Can't enroll for Xiaomi Redmi 6 OS: MIUI 11. Always receive error message "Can't set up device, Couldn't connect to Wi-Fi" even wifi already connected. Please see the attached photo for detail

![IMG_9484](https://user-images.githubusercontent.com/20983904/104310831-f4ca5e80-5506-11eb-9054-26d8c199aa3e.jpg)
![IMG_9485](https://user-images.githubusercontent.com/20983904/104310843-fac03f80-5506-11eb-8b98-14447bec58be.jpg)

**Comment by DarkSherlock** [comment]
:-(, I am blocked in the first step. where did you click to trigger the enrollment

**Comment by jscott1989** [comment]
If this only happens on Xiaomi devices it's likely not a TestDPC issue
