### ISSUE TITLE
Not able to run/install the code from Android studio , compilation works but when trying to install it gives issues

### ISSUE THREAD

**Issue by Amit1487** [googlesamples/android-testdpc#129]
1) Unable to resolve dependency for ':TestDPC@replicaRelease/compileClasspath': Could not resolve androidx.constraintlayout:constraintlayout:2.0.4.
Like this for all the dependencies it gives issue while installing/runing from android studio

2) Could not determine the dependencies of task ':TestDPC:lintNormalDebug'.
> Could not resolve all artifacts for configuration ':TestDPC:normalDebugCompileClasspath'.
   > Could not resolve androidx.lifecycle:lifecycle-extensions:2.3.1.
     Required by:
         project :TestDPC
         more lines liek this
         
         
         3) Last line of error is 
> Could not resolve androidx.constraintlayout:constraintlayout:2.0.4.
         > Could not get resource 'https://maven.google.com/androidx/constraintlayout/constraintlayout/2.0.4/constraintlayout-2.0.4.pom'.
            > Could not HEAD 'https://maven.google.com/androidx/constraintlayout/constraintlayout/2.0.4/constraintlayout-2.0.4.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Amit1487** [comment]
Compilation time syncing is working fine but these dependencies gives warning (same warning i.e. can not resolve) in compilation as well.

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
