### ISSUE TITLE
App management bug

### ISSUE THREAD

**Issue by guanhuay** [googlesamples/android-testdpc#13]
Hi:
just found a issue with testDPC Apps management.
Step to reproduce:
1. Install Blackberry Hub+ Services from Google Play Store
2. go into testDPC and click on "Enable system apps" under "Apps management" and select "Blackberry Hub+ Services".
3. click on "Manage app restrictions". (this is where the problem pop up).

at step 3, i could not locate Blackberry Hub+ Services.  such that i could not proceed to "Load Manifest Restrictions".

Any idea on what is going on here?

Thanks for your guys assistant.

**Comment by ming030890** [comment]
It is a bug in ManageAppFragment.java, we only return a list of app that having launcher icon. 
As a workaround, you could modify ManageAppFragment.getInstalledOrLaunchableApps.
Filed an internal bug to track this.

Thanks

**Comment by guanhuay** [comment]
@ming030890 thank for the walk around advise, my issue is now fixed!
