### ISSUE TITLE
Password Lock for Test DPC App (Please) 

### ISSUE THREAD

**Issue by alieren3453** [googlesamples/android-testdpc#131]
Hi, I know that this request might seem you unnecessary but please add this feature. I'm trying to get rid of my PMO addiction. I'm working on several Parental Control/Porn Block apps for 2 weeks. I'm about to complete. I setted everything up. Buti unfortunately I can access to test dpc. Any of 3rd party app lock apps can be bypassed using pop up view feature in Samsung phones. Can you, please, add this feature. I just need to lock Test DPC then I'm free!

**Comment by rkd628** [comment]
Testdpc  is just designed for testing device policy control api.
It seems good to implement the function you want by referring to this app code.

**Comment by alieren34** [comment]
> Hi, Testdpc is just designed for testing device policy control api.
> It seems good to implement the function you want by referring to this app code.

Hi! It's me again. I need this feature so much so can you please add this feature with Android 12 update for app? I can't implement this feature myself because I don't have any programming knowledge. I tried to implemet and build this feature myself but I was unsucessful. I downloaded Android Studio etc. but always failed.

**Comment by John889** [comment]
Adding a password lock would be super helpful!

**Comment by jscott1989** [comment]
This won't be added. You can fork the TestDPC code to try to do this if you like but it doesn't fit the goals of the project (which is to test device policy APIs)

**Comment by Jikodis** [comment]
@alieren34 , @alieren3453  Does this fork match your needs? Maybe worth a look.

https://github.com/routerdieb/pluckdpc

**Comment by hekawsh** [comment]
I made a fork, and I hope that works.

**Comment by clayliddell** [comment]
Just worked on creating a fork for this. Should work with Android 15+. Cheers

https://github.com/clayliddell/android-testdpc-require-password

**Comment by John889** [comment]
Try andoff

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hekawsh** [comment]
@hht355 I think you tried the wrong one, sorry for late reply...
If you downloaded the correct .apk file from the source tree (not added to releases), then the password can only be changed by uninstalling and reinstalling.
For using its features, you'll need to install Shizuku & Dhizuku (or ShizuShell) to give it "Device Owner" and/or through (wireless) ADB.

P.S: I'm not the owner of that software but the owner is probably the one above my initial comment.

**Comment by sikotat** [comment]
@clayliddell 
1. App lock feature doesn't work in TestDPC fork that You created. I'm on Android 16(Samsung Galaxy A25 5G).It asks for a password when I open the app for the first time, but after the first time, it doesn't ask for a password. I can change any option and even uninstall TestDPC.
2. Another feature I would like to see is to ask for password when I return to TestDPC. For example, when I minimize the app and enter the app again from Recent Apps (Recent navigation bar button), TestDPC asks again for a password.

**Comment by sikotat** [comment]
@hekawsh 

Your TestDPC fork is on version 8.0.0, this is the old version, please update to the newest version.

We can only use generated password to enter the app. Please make, so that we can put our own password, instead of the generated. Currently, If we change the generated password or set our own password, we can't enter the app.
