### ISSUE TITLE
DPC - How to test code paths for QR/Zero Touch Device Owner setup?

### ISSUE THREAD

**Issue by mattylase** [googlesamples/android-testdpc#133]
Sorry to any googlers as this likely isn't the right venue.

Can anyone explain exactly how the app is launched in Zero Touch and Device Owner QR Code enrollment? I understand that an intent is sent, and will contain the `PROVISIONING_ADMIN_EXTRAS_BUNDLE` - that's all quite straightforward, but I'm not sure exactly *where* the intent should be handled, given that provisioning happens immediately upon device startup and it's not feasible to debug.

Any advice - intent filter, class, etc. would be helpful.

**Comment by jscott1989** [comment]
Back in Android 10, TestDPC was updated in accordance to [this guide](https://developer.android.com/work/versions/android-10#improved_provisioning_tools_for_work_profiles). In summary, there are 2 entry points to TestDPC: the `android.app.action.GET_PROVISIONING_MODE`, which requests the DPC to return the desired provisioning mode (work profile or device owner), and `android.app.action.ADMIN_POLICY_COMPLIANCE`, which allows the DPC to set itself up after it has been made a profile owner/device owner.
This is the case for ZeroTouch and QR enrollment, and we're migrating all of the other flows to follow this pattern as well. For managed account provisioning, pre-Android 12 it's only launched after provisioning it's launched via the `android.app.action.PROVISIONING_SUCCESSFUL` intent, and from Android 12 onward it's started just like ZeroTouch and QR enrollment. For NFC provisioning it's also only started via `android.app.action.PROVISIONING_SUCCESSFUL`, which will also be updated in the upcoming Android release to be like ZeroTouch and QR enrollment.

**Comment by mattylase** [comment]
Hey @jscott1989 - sorry for the ping, but I'm a little confused around Android 12.

In trying to use the link you provided, along with what's provided in [deprecations list](https://developer.android.com/work/versions/android-12), as well as the [official documentation](https://developers.google.com/android/work/play/emm-api/prov-devices#qr_code_provisioning_process), I'm not able to enroll via QR code. The official docs seem to still describe the deprecated process, so I'm at a loss for how to troubleshoot.

I've got an activity (essentially a 1:1 copy of what is in this repository) responding to intents of `GET_PROVISIONING_MODE`, however I get a dialog that says "Can't Set Up Device - Can't use the admin app. It's missing components or corrupted". This said, I have tested the same QR code via the pre-12 flow, and am able to enroll fine. I am just executing the typical QR code enrollment instructions outlined in the official documentation and run into this failure.

For reference, here's the JSON for my QR code, if it helps:

```
{
    "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "https://storage.googleapis.com/test-apk/my-prod-release.apk",
    "android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "7k3c7PXdutI2axrbTDeqS5lu5dUm3mDg1f-D072ABr0=",
    "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM": "KylVP0_l3MZ9B_mSsAMTtZ-QZM0_8YsMHFE3p51NRyg",
    "android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.mycompany/.DeviceAdmin",
    "android.app.extra.PROVISIONING_ADMIN_EXTRAS_BUNDLE": {
        "network_id": "lasernet"
    }
}
```

Is there any place where specific, up to date steps are enumerated? Or some way I'm able to debug this behavior given I can't enable USB debugging after a factory reset? I am able to do QR provisioning using the actual TestDPC app and QR code provided in the `README`, but I don't know how to determine what is going wrong with my application.

Any input is appreciated.

**Comment by paolominel** [comment]
I've got same issue...
I also tried to build testDPC from this repository but when I try to install it via qrcode on target device i receive "Can't Set Up Device - Can't use the admin app. It's missing components or corrupted" error.
Can you provide a simple and clear flow to enroll a device with qrcode and custom dpc app (i need to use a device policy manager features that i cannot inherit by delegated scope)

**Comment by jscott1989** [comment]
Create a local server that serves your custom TestDPC or upload it somewhere publicly
Make sure you can actually access the TestDPC apk from the phone
Get the SHA-256 checksum of the apk; on Linux you can use sha256sum path/to/TestDPC.apk
Create a QR code with the following content:
{
	"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.afwsamples.testdpc/com.afwsamples.testdpc.DeviceAdminReceiver",
	"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM": "apk checksum from step 3",
	"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "url that serves your TestDPC"
}
From the SetupWizard Welcome screen tap 6 times to launch the QR code scanner
Scan QR code
