### ISSUE TITLE
Missing sources for 8.0.1

### ISSUE THREAD

**Issue by MizunSD** [googlesamples/android-testdpc#135]
I found that apk version (http://down-box.appspot.com/qr/nQB0tw7b) is 8.0.1 and in repo tags 8.0.0 and 8.0.1 assigned to the same commit with build.gradle contains:
```
    // 1 or more digits
    versionMajor = 8
    // exactly 1 digiT
    versionMinor = 0
    // exactly 2 digits
    versionBuild = 00
```

I think some commits are missing, because:
1) I make release build signed with my key
2) Generate own QR with new checksum and file link
3) Got an error while provisioning device with Android 12

**Comment by MizunSD** [comment]
Just saw your answer 
https://github.com/googlesamples/android-testdpc/issues/134#issuecomment-947629937

May be you can tell me what to add to 8.0.0 version to make it works on Android 12?
Thank you in advance!

**Comment by jscott1989** [comment]
Sorry this is taking a while. Some other stuff has come up.

There's only one major change between 8.0.00 and 8.0.1:

```
--- a/app/src/main/java/com/afwsamples/testdpc/policy/PolicyManagementFragment.java
+++ b/app/src/main/java/com/afwsamples/testdpc/policy/PolicyManagementFragment.java
@@ -608,10 +608,10 @@
                 MUTE_AUDIO_KEY);
         mMuteAudioSwitchPreference.setOnPreferenceChangeListener(this);
 
-        mPreferentialNetworkServiceSwitchPreference = (SwitchPreference) findPreference(
+        if (mIsProfileOwner && Util.SDK_INT >= VERSION_CODES.S) {
+            mPreferentialNetworkServiceSwitchPreference = (SwitchPreference) findPreference(
                 SET_GET_PREFERENTIAL_NETWORK_SERVICE_STATUS);
-        mPreferentialNetworkServiceSwitchPreference.setOnPreferenceChangeListener(this);
-        if (mIsProfileOwner) {
+            mPreferentialNetworkServiceSwitchPreference.setOnPreferenceChangeListener(this);
             mPreferentialNetworkServiceSwitchPreference.setChecked(
                     mDevicePolicyManagerGateway.isPreferentialNetworkServiceEnabled());
         }
```

That should fix it for you

**Comment by MizunSD** [comment]
Thanks for your reply!

I found the problem in my code: looks like I need to set `android:testOnly="false"`, but I didn't find any information about it. On pre-12 everything worked fine with default value (may be it will help someone else)
