### ISSUE TITLE
When can I perform post-provisioning operations?

### ISSUE THREAD

**Issue by mattylase** [googlesamples/android-testdpc#139]
For a QR Code Device owner enrollment on an Android 12 device, I need to perform certain operation, like register the device with my EMM portal via API.

When should this be done?

We have previously used the intents `ACTION_PROVISIONING_COMPLETE` delivered to the Device Admin, and `ACTION_PROVISIONING_SUCCESSFUL` as well, but they don't seem to be working currently.

In this repo, [this line](https://github.com/googlesamples/android-testdpc/blob/cf9374bc4c7d1a548bbeb8d9bd05828a9d05cd66/app/src/main/java/com/afwsamples/testdpc/DeviceAdminReceiver.java#L135) immediately bails out of the `ACTION_PROVISIONING_COMPLETE` flow, so it appears to me that I shouldn't use it. I have no idea what issue that this comment is intending to reference.

As for `ACTION_PROVISIONING_SUCCESSFUL`, it's never launched for me - and it appears to be an issue affecting others on [StackOverflow](https://stackoverflow.com/questions/69452774/android-12-provisioning-successful-intent-never-received) and has [an open issue](https://issuetracker.google.com/issues/201968957) in Google's own issue tracker.

Any guidance is appreciated - this issue is blocking all new enrollments for our customers.

**Comment by nithin-kande** [comment]
Hi Mattylase,

Having this issue and no where documented. Any updates on this issue?

Thanks.

**Comment by jscott1989** [comment]
See https://developer.android.com/work/versions/android-10#improved_provisioning_tools_for_work_profiles

`android.app.action.ADMIN_POLICY_COMPLIANCE` is what you need.
