### ISSUE TITLE
Remove profile owner

### ISSUE THREAD

**Issue by nin0-dev** [googlesamples/android-testdpc#140]
Hi.

I needed to test something as profile owner (not work profile, my main profile) Apparently it was a stupid mistake, as now I'm stuck with this app.

Any way I can disconnect the app as profile owner?

**Comment by nin0-dev** [comment]
At least set it as test.

**Comment by empratyush** [comment]
App drawer -> Tes DPC -> "remove this device owner" should do the trick afaict.

**Comment by nin0-dev** [comment]
> App drawer -> Tes DPC -> "remove this device owner" should do the trick afaict.

No. The app is set as PROFILE owner, not DEVICE owner.


But I managed to get rid of it with root and removing the APK w/ file manager.
