### ISSUE TITLE
Android studio gradle and jdk version troubleshooting

### ISSUE THREAD

**Issue by clonedSemicolon** [googlesamples/android-testdpc#144]
I have an old project where the Gradle version of 4.4 is used. I tried to build the project in the recent version of the android studio where JDK 11 is used. So, it gives the below error:

```Unable to start the daemon process.

The project uses Gradle 4.4 which is incompatible with Java 11 or newer.
```

So, I needed to downgrade the JDK version. Changed the jdk version to 8 in the android studio. Because the Gradle dependencies could not be updated as there were a lot of dependencies there. But now the build provides these following error: 
```
cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.

```
Is there any solution for that without changing the gradle version as i said there were a lot of dependencies

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
