### ISSUE TITLE
can't select work files in Work profile  from  personal side

### ISSUE THREAD

**Issue by charleschao2009** [googlesamples/android-testdpc#146]
I have added the below cross-profile intents successfully
Flags : FLAG_MANAGED_CAN_ACCESS_PARENT
Actions: android.intent.action.VIEW
Categories : android.intent.category.DEFAULT
Schemes: http
Data types: */*

when I opened the gmail then composed an email and  added Attach file ,it would open the files page, but after selected the Work tab
it turned out:

Can't select work files
Your IT admin doesn't allow you to access work files from a personal app

why couldn't access the file in  Work profile  from the app in  Personal side?

**Comment by jscott1989** [comment]
This is an issue with Enterprise generally not TestDPC.

[My guess from a very quick look is that your flag is wrong. becasue it only allows work->personal?)

**Comment by charleschao2009** [comment]
> 

yeah,  the description of FLAG_MANAGED_CAN_ACCESS_PARENT from google doc is that:
 /**
     * Flag used by {@link #addCrossProfileIntentFilter} to allow activities in
     * the managed profile to access intents sent from the parent profile.
     * That is, when an app in the parent profile calls
     * {@link Activity#startActivity(Intent)}, the intent can be resolved by a
     * matching activity in the managed profile.
     */
  what I  want is that the app in the personal side could access the file from work profile so the flag I added is correct

**Comment by LarveyOfficial** [comment]
@charleschao2009 did you ever figure this out?
