### ISSUE TITLE
找不到对应依赖

### ISSUE THREAD

**Issue by yong396040003** [googlesamples/android-testdpc#147]
android.app.admin.PreferentialNetworkServiceConfig

错误: 找不到符号
import android.app.admin.PreferentialNetworkServiceConfig;
                        ^
  符号:   类 PreferentialNetworkServiceConfig
  位置: 程序包 android.app.admin

**Comment by yong396040003** [comment]
新人有点不懂请求大佬讲解

**Comment by jscott1989** [comment]
https://developer.android.com/reference/android/app/admin/PreferentialNetworkServiceConfig this class exists. Are you building against the latest T SDK?

**Comment by yong396040003** [comment]
![2022-05-12 13-23-03 的屏幕截图](https://user-images.githubusercontent.com/40829642/167997978-e4b69b52-f151-44e7-aa32-ae037c643c21.png)
当前目标版本是31，但是DevicePolicyManager能找到，理论上来说它们实在同一个包应用下的

**Comment by jscott1989** [comment]
target sdk doesn't matter - but you need to make sure you have the T SDK (33) to build against otherwise it can't find the new classes.
