### ISSUE TITLE
Unable to make android 12 fully owned device owner

### ISSUE THREAD

**Issue by AmanArora1987** [googlesamples/android-testdpc#154]
I am trying to making my device Pixel 4A android 12 to fully owned device, But i am stucking after scanning QR code with error "can't set up device contact your IT admin for help" but similar config is working fine in Android 9.0(Xiaomi MI A2)

**Comment by Jamshid-M** [comment]
@AmanArora1987 you need to init android.app.action.GET_PROVISIONING_MODE in manifest also if you want you can also set android.app.action.ADMIN_POLICY_COMPLIANCE, you can see in this repo two activities FinalizeActivity and GetProvisioningModeActivity, after scanning QR, first launch GetProvisioningModeActivity you can get here all info from QR, also if you setup FinalizeActivity here also info from QR is available, then from here you can enroll your device

**Comment by aloz77** [comment]
@Jamshid-M How do you get the info from QR code in GetProvisioningModeActivity exactly? The intent looks like this and doesn't seem to contain any information from QR code. I need to get the PROVISIONING_ADMIN_EXTRAS_BUNDLE from QR code in Android 12.

`intent:#Intent;action=android.app.action.GET_PROVISIONING_MODE;package=com.mypackage.emm;component=com.mypackage.emm/de.mypackage.emm.GetProvisioningModeActivity;B.isSetupFlow=true;S.android.app.extra.PROVISIONING_IMEI=XXXXXXXXXX;B.preDeferredSetup=false;B.deferredSetup=false;B.firstRun=true;B.portalSetup=false;S.theme=glif_v3_light;S.android.app.extra.PROVISIONING_SERIAL_NUMBER=XXXXXXXXXX;B.android.app.extra.PROVISIONING_SENSORS_PERMISSION_GRANT_OPT_OUT=false;end`

**Comment by Jamshid-M** [comment]
@aloz77 Both GetProvisioningModeActivity and Finalize activities contain intent.getParcelableExtra(EXTRA_PROVISIONING_ADMIN_EXTRAS_BUNDLE)
and inside this extra contains info provided in QR code
Maybe you didn't give the correct intent filters

**Comment by aloz77** [comment]
@Jamshid-M Thank you, this works
