### ISSUE TITLE
FATAL error caused from missing resource 

### ISSUE THREAD

**Issue by jindog** [googlesamples/android-testdpc#155]
By following build instruction on issue #150 , I got the testdpc apk for Android 13 finally. 
I installed it on Pixel device (with Android 13 beta3) and got FATAL crash whenever trying to set up work profile   

It seems that the root cause of this layout failure is related to "android.support.v7.widget.AppCompatTextView" included in 'setupdesign.aar'. 
Can you replace it with androidx, or make appropriate fix on buildscript ? 

06-09 16:45:44.440 23112 23112 E AndroidRuntime: FATAL EXCEPTION: main
06-09 16:45:44.440 23112 23112 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 23112
06-09 16:45:44.440 23112 23112 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afwsamples.testdpc/com.afwsamples.testdpc.SetupManagementActivity}: android.view.InflateException: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Error inflating class com.google.android.setupdesign.GlifLayout
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3686)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7886)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-09 16:45:44.440 23112 23112 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Error inflating class com.google.android.setupdesign.GlifLayout
06-09 16:45:44.440 23112 23112 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Error inflating class com.google.android.setupdesign.GlifLayout
06-09 16:45:44.440 23112 23112 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at com.afwsamples.testdpc.SetupManagementFragment.onCreateView(SetupManagementFragment.java:106)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.Fragment.performCreateView(Fragment.java:2505)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8276)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8247)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1371)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3667)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
06-09 16:45:44.440 23112 23112 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7886)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-09 16:45:44.441 23112 23112 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24 in com.afwsamples.testdpc:layout/sud_glif_template: Binary XML file line #57 in com.afwsamples.testdpc:layout/sud_glif_header: Error inflating class com.google.android.setupdesign.view.RichTextView
06-09 16:45:44.441 23112 23112 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #57 in com.afwsamples.testdpc:layout/sud_glif_header: Error inflating class com.google.android.setupdesign.view.RichTextView
06-09 16:45:44.441 23112 23112 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.setupdesign.view.RichTextView
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at java.lang.Class.forName(Class.java:454)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:819)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupcompat.internal.TemplateLayout.inflateTemplate(TemplateLayout.java:177)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupdesign.GlifLayout.onInflateTemplate(GlifLayout.java:286)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupcompat.internal.TemplateLayout.inflateTemplate(TemplateLayout.java:141)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupcompat.internal.TemplateLayout.init(TemplateLayout.java:83)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupcompat.internal.TemplateLayout.<init>(TemplateLayout.java:62)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupcompat.PartnerCustomizationLayout.<init>(PartnerCustomizationLayout.java:101)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.google.android.setupdesign.GlifLayout.<init>(GlifLayout.java:98)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at com.afwsamples.testdpc.SetupManagementFragment.onCreateView(SetupManagementFragment.java:106)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.Fragment.performCreateView(Fragment.java:2505)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
06-09 16:45:44.441 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8276)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8247)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1371)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3667)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7886)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-09 16:45:44.442 23112 23112 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.setupdesign.view.RichTextView
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        ... 59 more
06-09 16:45:44.442 23112 23112 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/AppCompatTextView;
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        ... 59 more
06-09 16:45:44.442 23112 23112 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.AppCompatTextView" on path: DexPathList[[zip file "/data/app/~~Vr7hyKBIe9LPHacC7UEmsQ==/com.afwsamples.testdpc-dIis3-Zffey9jOZHZbQz8Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~Vr7hyKBIe9LPHacC7UEmsQ==/com.afwsamples.testdpc-dIis3-Zffey9jOZHZbQz8Q==/lib/arm64, /system/lib64, /system_ext/lib64]]
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-09 16:45:44.442 23112 23112 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by rkd628** [comment]
That issue happens to me also.

**Comment by jscott1989** [comment]
That's weird - as it has built successfully for other people. I'll try to find time to reproduce this myself soon.

**Comment by pcrepieux** [comment]
Any update on this ? I am facing the same issue.

**Comment by vdomak** [comment]
May I know is there any update on this issue?

**Comment by jscott1989** [comment]
Fixed - try building again
