### ISSUE TITLE
Private DNS Not Locking on Android 12

### ISSUE THREAD

**Issue by hpoissant** [googlesamples/android-testdpc#157]
I'm using a T-Mobile Oneplus 9 running Android 12 (Oxygen OS 12 LE2117_11C.18). With Android 11, the setting to lock the private DNS worked perfectly but it seems since "upgrading" to Android 12, this feature is no longer working. I am able to set a private DNS and change it as often as I would like through the settings menu as if the testdpc configuration was not in effect.

**Comment by jscott1989** [comment]
This isn't a TestDPC bug. Please open the bug with Oneplus
