### ISSUE TITLE
How To Remove Redundant TestDPC function?

### ISSUE THREAD

**Issue by guanhuay** [googlesamples/android-testdpc#16]
Hi all:

Right now i am trying to remove some TestDPC function that i don't want. For example, "Camera,screen,capture and audio" and "Certificate management".

The file i modified is: 
1. profilepolicy/ProfilePolicyManagementFragment.java
2. res/xml/device_policy_header.xml

However, the problem is: when i delete the related code, and build the project, it shows no error, which means i am good to go. But when i load the apk into my device and try to open it. It cannot, it just crash without any prompt.

So any ideas on how to delete the functions?

Thanks.

**Comment by guanhuay** [comment]
The error i got from bugreport is:

10-06 15:55:50.269 12274 12274 E AndroidRuntime: FATAL EXCEPTION: main
10-06 15:55:50.269 12274 12274 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 12274
10-06 15:55:50.269 12274 12274 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afwsamples.testdpc/com.afwsamples.testdpc.PolicyManagementActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.preference.Preference.setOnPreferenceChangeListener(android.support.v7.preference.Preference$OnPreferenceChangeListener)' on a null object reference
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.preference.Preference.setOnPreferenceChangeListener(android.support.v7.preference.Preference$OnPreferenceChangeListener)' on a null object reference
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at com.afwsamples.testdpc.policy.PolicyManagementFragment.onCreatePreferences(PolicyManagementFragment.java:383)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.support.v14.preference.PreferenceFragment.onCreate(PreferenceFragment.java:231)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at com.afwsamples.testdpc.common.BaseSearchablePolicyPreferenceFragment.onCreate(BaseSearchablePolicyPreferenceFragment.java:37)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at com.afwsamples.testdpc.policy.PolicyManagementFragment.onCreate(PolicyManagementFragment.java:308)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2335)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:880)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:727)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:371)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6721)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
10-06 15:55:50.269 12274 12274 E AndroidRuntime: 	... 9 more

**Comment by hex539** [comment]
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.preference.Preference.setOnPreferenceChangeListener(android.support.v7.preference.Preference$OnPreferenceChangeListener)' on a null object reference

You'll also need to remove any Java code that references the preference keys you deleted from XML, or it will try to load them and set listeners at runtime, which as you can see will fail because they don't exist.

We should handle this gracefully in every case, but it's more of a nice-to-have as the app hasn't been designed to handle having preferences removed.
