### ISSUE TITLE
tethering can't  turned off

### ISSUE THREAD

**Issue by intpython** [googlesamples/android-testdpc#162]
I use samsung phone and android is 11，I turn on tethering on my phone and then I go to the "Disallow config tethering" button, my tethering county is restricted, but tethering is still on。

**Comment by jscott1989** [comment]
That sounds like works as intended - you've disallowed configuring tethering - not disabled tethering.

Either way - this isn't a TestDPC issue. If the API isn't working correctly, open an issue with Samsung.
