### ISSUE TITLE
document source of mystery setup lib AARs

### ISSUE THREAD

**Issue by eighthave** [googlesamples/android-testdpc#165]
This project is listed as having an Apache-2.0 license.  The last release (v8.0.1) included a binary lib _app/libs/setup-wizard-lib-platform-release.aar_.  _master_ includes three:

* _lib/setupcompat.aar_
* _lib/setupdesign.aar_
* _lib/strings.aar_

The only documentation I could find about what these are and where they came from is from a commit message:

>    Use the setup wizard library from AOSP.
>    
>    There are two build variants of setup wizard library available.
>   platformRelease: minSdkVersion 21
>    icsCompatRelease: minSdkVersion 14
>    Since TestDPC is not expected to run on pre-L, platformRelease
>    will work just fine.
>    
>    Bug: 24534771
>    Change-Id: I3b8554a408f78ea391ce6f0d536ea6a8c16d6798

Something about the repo used (is it https://android.googlesource.com/platform/frameworks/opt/setupwizard/?) and tag/branch built would be very helpful to ensure that this app is actually all Apache-2.0 licensed.

**Comment by jscott1989** [comment]
Setupcompat built from https://cs.android.com/android/platform/superproject/+/master:external/setupcompat/Android.bp;l=68
Setupdsign and strings built from https://cs.android.com/android/platform/superproject/+/master:external/setupdesign/Android.bp;l=28

I'll add the information to a readme alongside the aars

**Comment by eighthave** [comment]
Sounds good!  Do you have a link to the source that belongs to _app/libs/setup-wizard-lib-platform-release.aar_?  I'd like to try building that now, since that's what's used in the latest release.

**Comment by jscott1989** [comment]
Sorry which file? I don't see that...

I've had some issues with the prebuilts recently so thinking of mirroring the code from AOSP in here then I can directly depend on it - that should deal with your issue too

**Comment by eighthave** [comment]
This is the file:
https://github.com/googlesamples/android-testdpc/commits/master/app/libs/setup-wizard-lib-platform-release.aar

It is used in the release that is currently up on https://play.google.com/store/apps/details?id=com.afwsamples.testdpc

**Comment by jscott1989** [comment]
Oh sorry I don't know as that predates me. I assume it's just a previous library which became setupcompat/etc.

**Comment by eighthave** [comment]
Ok, any way to find out from previous maintainers?  Or are you planning a new 
release soon?

**Comment by jscott1989** [comment]
We'll be releasing as soon as we can get our release pipeline moving again - but right now our Android framework deadlines are the priority so it's been pretty delayed.

When we release it will match the current state of the github code though.

**Comment by pfmaggi** [comment]
The new v9.0.1 currently on the [Play Store][1] doesn't depends anymore on `setup-wizard-lib-platform-release.aar`

[1]: https://play.google.com/store/apps/details?id=com.afwsamples.testdpc
