### ISSUE TITLE
Occur fatal exception in removing widgets which is added previously

### ISSUE THREAD

**Issue by dsdlsu** [googlesamples/android-testdpc#17]
[bugreport-NPF10C-2016-11-04-21-01-33.zip](https://github.com/googlesamples/android-testdpc/files/571403/bugreport-NPF10C-2016-11-04-21-01-33.zip)

Dear developer.

I found a bug like below error logs, please check it.
11-04 21:00:55.953  7743  7743 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 7743
11-04 21:00:55.953  7743  7743 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageDrawable(android.graphics.drawable.Drawable)' on a null object reference
11-04 21:00:55.953  7743  7743 E AndroidRuntime: 	at com.afwsamples.testdpc.common.AppInfoArrayAdapter.getView(AppInfoArrayAdapter.java:67)

[Reproduce]
1. Install any application from Google play store(ex, timesheet)
2. Enable app widget what I installed
3. Uninstall the app
4. Try to insert the "Remove app widgets in a work profile app" menu
5. Fatal exception.

I attached bugreport inlcude the fatal exception log.

Thank you.

**Comment by ming030890** [comment]
Thanks for reporting, bug is tracked internally.
