### ISSUE TITLE
PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM shows an error of checksum

### ISSUE THREAD

**Issue by makri-aymen** [googlesamples/android-testdpc#170]
I download the app from "https://testdpc-latest-apk.appspot.com" and I set it on my IIS Windows, and I get the PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM with this command 
cat TestDPC_8001.apk | openssl dgst -binary -sha256 | openssl base64 | wsl tr '+/' '-_' | wsl tr -d '='
so final result of the qr-code becomes like this

{
"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME":"com.afwsamples.testdpc/com.afwsamples.testdpc.DeviceAdminReceiver",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM":"MS4_Pz8gP0VDPy0_P2I_Pz4NClE_Pz80Pz8rPz9zfD8_DQo",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION":"http://192.168.1.224/TestDPC_8001.apk"
}

**Comment by AdarshRevankar** [comment]
Anyone is aware of a guide to create this `PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM` ? 

Struggling to make my custom app to install via qr provisioning :(
