### ISSUE TITLE
Sample .bazelproject

### ISSUE THREAD

**Issue by challgren** [googlesamples/android-testdpc#174]
I'd like to work on this project in Android Studio but I'm having issues getting Bazel to sync correctly. Can you please provide your `.bazelproject` file so I can try to figure out how to get it to sync correctly in Android Studio

**Comment by mddanishansari** [comment]
@challgren did you find a solution for this? If you were able to import the project in Android Studio, can you please help me?

**Comment by challgren** [comment]
> @challgren did you find a solution for this? If you were able to import the project in Android Studio, can you please help me?

I never did get it to work correctly. I ended up solving my issue by correctly implementing the new Permissions
