### ISSUE TITLE
Anyone help me to create an app using testdpc

### ISSUE THREAD

**Issue by Ammypartner** [googlesamples/android-testdpc#177]
Hi i want to create an app using testdpc

**Comment by HradeshKumar** [comment]
are you able to find any solution to create Test DCP?.

**Comment by Ammypartner** [comment]
No

**Comment by pfmaggi** [comment]
Closing this as there not enough information to provide any guidance.

If you still have an issue with TestDPC, please open a new bug and provide detailed information of that the issue is.
