### ISSUE TITLE
How to distinguish personal and work user

### ISSUE THREAD

**Issue by guanhuay** [googlesamples/android-testdpc#18]
Hi Developer,

i just facing a issues, here is the scenario:

if i create a profile owner(have both personal and work space), if i install a CA certificate to the work profile. How can i tell from logcat this certificate is really install to the work profile.

In this case, what keyword should i apply?

Thanks for your answer.

**Comment by ming030890** [comment]
Settings->Security->Trusted credentials->User
You should see dual pane, personal and work.
I am not sure is it available in pre-N though :)

![screen](https://cloud.githubusercontent.com/assets/2291115/20214057/b419dd5c-a803-11e6-9145-42065d71268d.png)
