### ISSUE TITLE
Some strings seem awkward 

### ISSUE THREAD

**Issue by jindog** [googlesamples/android-testdpc#19]
For the 'reset password' policy, testdpc shows below strings as options for the method. 

    <string name="require_password_entry">Require strongest available authentication type on next unlock</string>
    <string name="require_password_on_boot">Require password to start user</string>

But, I think that these strings are not matched with the definition of DevicePolicyManager 
https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#RESET_PASSWORD_REQUIRE_ENTRY
https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#RESET_PASSWORD_DO_NOT_ASK_CREDENTIALS_ON_BOOT

1) "require_password_entry" is not related to 'strongest available auth type' 
2) "require_password_on_boot" option should be changed to "require_NO_password_on_boot"

**Comment by ming030890** [comment]
Thanks for reporting.
Tracked internally, closing this out.
