### ISSUE TITLE
No toolchains found

### ISSUE THREAD

**Issue by Twibap** [googlesamples/android-testdpc#195]
Hi, I get a message about toolchain.

```prompt
INFO: ToolchainResolution:   Type @bazel_tools//tools/android:sdk_toolchain_type: target platform @local_config_platform//:host: No toolchains found.
ERROR: /android-testdpc/BUILD:73:15: While resolving toolchains for target //:testdpc: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
```

so I query to `@local_config_platform//:host` and `@bazel_tools//tools/android:sdk_toolchain_type`

this is the result

```prompt
# /private/var/tmp/_bazel.../external/local_config_platform/BUILD.bazel:4:9
platform(
  name = "host",
  constraint_values = ["@platforms//cpu:x86_64", "@platforms//os:osx"],
)
# /private/var/tmp/_bazel.../external/bazel_tools/tools/android/BUILD:7:15
toolchain_type(
  name = "sdk_toolchain_type",
)
```

I tried the result copy & paste into /android-testdpc/BUILD:72
result nothing changed.

os: osx
bazel version : 6.4.0 & 6.3.2 & 5.3.0

**Comment by pfmaggi** [comment]
To compile TestDPC you need to have the Android SDK correctly setup and with the toolchain available. 
You can use Android Studio with the Bazel plugin, as explained in the readme, to compile TestDPC.

Android Studio setup will guide you to install the Android SDK and toolchain.
