### ISSUE TITLE
Test device owner provisioning on device without NFC

### ISSUE THREAD

**Issue by Blystad** [googlesamples/android-testdpc#2]
Hello,

How can I test device owner provisioning on a device without NFC?

According to https://source.android.com/devices/tech/admin/provision.html it should be supported:

>Device Owner Provisioning with Activation Code
>Select Add Work Account from the setup wizard. This triggers a lookup of the EMM from Android servers.
>
>The device installs the EMM app and starts provisioning flow. As an extra option, Android device administration supports the option of using email address with a six-digit activation code to bootstrap the process as part of setup wizard.

**Comment by crowfeather** [comment]
Thanks for flagging that page as it's out of date. Yes, there are other ways to test device owner provisioning:

1. Android 5.0 and 5.1 devices: using activation codes provided by an Enterprise Mobility Management (EMM) company
2. Android 5.1+: Google account provisioning after linking your domain to an EMM
3. ADB (on all versions of Android): $ adb shell dpm set-device-owner "com.afwsamples.testdpc/.DeviceAdminReceiver"

Given that you need an EMM (among other things) in the first two scenarios, I think option 3 will serve you best. Feel free to reach out with further questions. Thanks!

**Comment by Blystad** [comment]
Thanks, that worked.

**Comment by leemangkit** [comment]
I face similar problem in testing device owner provisioning:. I understand device owner should setup with factory reset of phone. Just don't know when I should send the adb comand "ADB (on all versions of Android): $ adb shell dpm set-device-owner "com.afwsamples.testdpc/.DeviceAdminReceiver" over setup wizard flow.

By the way, if my device is not in ENG mode, the adbd is not yet working in setup wirard, How I can get the activation codes provided by an Enterprise Mobility Management (EMM) company???

I already create a domain as subscript to AFW already, EMM is google MDM. I try contact to google help desk, however, still don't know how I can get the activation code.

**Comment by crowfeather** [comment]
To the the adb command, follow these steps:

1) Factory reset your device (running Android 5.0+). Don't leave the language selection screen in the setup wizard.
2) Install Test DPC via adb: adb install <apk location>
3) Set Test DPC as the device owner via adb: $ adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver
4) Go through the setup wizard as normal. When you're finished, Test DPC will be set as the device owner.

Note that you can use this whether your device has an eng or userdebug build installed.

Unfortunately, it looks like we don't have an EMM that ended up implementing activation codes (including Google's EMM who's DPC is called Google Apps Device Policy). Activation codes were deprecated with Android 5.1, and in turn, Google account provisioning was implemented instead. 

Let me know if you have further questions. Thanks!

-Brandon

**Comment by leemangkit** [comment]
Hi Brandon,

Thanks a lot for your explanation and I have not more question now.

leemangkit

**Comment by pliska87** [comment]
Hi crowfeather, 
i have problems setting the device owner to my app, because give me this error: 
**Trying to set device owner but device is already provisioned.**
Even if i perform a factory reset, install app and try to apply that code via ADB.

Only one thing i don't understand at your points:

1) Factory reset your device (running Android 5.0+). **Don't leave the language selection screen in the setup wizard.**
2) Install Test DPC via adb: adb install 


How can i install my app via adb if (since i'm in the language section screen in the setup wizard) i can't select developer mode?????
ADB do not recognise my device......how do you made that method?

Thank you!

**Comment by commonod** [comment]
Hello pliska87,
I am facing the same problem I think. when I try to install my app, it says 

error: device not found
-waiting for device- 

do you have a solution for this problem? Thanks a lot, cheers

**Comment by ming030890** [comment]
You can go through setup wizard as normal and enable usb debugging before running the adb command
`adb shell dpm set-device-owner `

**Comment by commonod** [comment]
hey ming030890,
thanks for your answer, according to this site https://source.android.com/devices/tech/admin/provision.html it is not possible:

> Note: The device owner can be set only from an unprovisioned device. If Settings.Secure.USER_SETUP_COMPLETE has ever been set, the device is considered provisioned and the device owner cannot be set.

And it looks like it is not possible for me. Is there any chance to enable usb debugging in the language selection screen?
cheers

**Comment by ming030890** [comment]
The error should be thrown only if you set device owner through DevicePolicyManager.setDeviceOwner, if you set through the adb command mentioned above, it should be fine.

Code Reference:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.0_r1/com/android/server/devicepolicy/DevicePolicyManagerService.java#4042

You can see this in the comment:
Device owner can only be set on an unprovisioned device, unless it was initiated by "adb", in which case we allow it if no account is associated with the device.

**Comment by ming030890** [comment]
Oh, is there any chance you added an account in setupwizard?
You can't setup device owner if you have account added.
Please skip adding account when you go through the setup wizard or remove the account in Settings before running the adb command
Hope it helps  👍

**Comment by commonod** [comment]
Thanks for your replies. No, I skipped everything, didn't even added my WiFi. 
That's what I do: I go through the setup wizard, add developer options, add the USB debugging, install the app and then I try to set the device owner and I get the error that I can only do it at unprovisioned phones. I rooted my app and there is no /system/data/device_owner.xml
My phone is a huawei y560-l01 with android 5.1
Cheers

**Comment by Blystad** [comment]
Check that you don't have any accounts at all in the Settings app. In my case we had an app that automatically created an account for a service on the first device boot.

**Comment by commonod** [comment]
Nope, Settings-> Accounts is empty...

**Comment by ming030890** [comment]
Hi commonod

Could you mind generating a bug report through adb bugreport command and attaching to here?
Not guarantee I can spot the issue though :)

**Comment by pliska87** [comment]
Hi commonod, i have your same problem with a Lenovo Tab2 A10-30 tablet with Android 5.1.1.
I made a factory reset, skip all settings in wizard (even the specification of an account), i enable usb debug, install my app, try to set the device owner via adb and the error that i have is this: 

_java.lang.IllegalStateException: Trying to set device owner but device is already provisioned.
        at android.os.Parcel.readException(Parcel.java:1554)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:3212)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:114)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:82)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.dpm.Dpm.main(Dpm.java:38)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)_

I'm fighting with this from a week, still NO SOLUTION!

**Comment by commonod** [comment]
Hey Pliska,
Thats exactly my error message. Don't know what is wrong...

@ming030890 I will do it on Thursday, I'm on my way at the moment.

**Comment by commonod** [comment]
[bugreport.txt](https://github.com/googlesamples/android-testdpc/files/474345/bugreport.txt)
attached my bugreport... not sure if i did it right. let me know. cheers

**Comment by ming030890** [comment]
In the log, you did have one account and I suspect it is a hidden account preloaded in your device.
You mention your device is rooted, could you do me a favor by running these commands?

adb shell
sqlite /data/system/0/accounts.db
select * from accounts;

=======================================
FYI, your log shows that you have one account
DUMP OF SERVICE account:
User UserInfo{0:Owner:13}:
  Accounts: 1

**Comment by commonod** [comment]
okay, I found the issue! in my Settings -> Security -> Device administrators there was already an entry for the Android Device Manager.
After deleting this app, I tried to set the device_owner via adb command. same problem. So I followed this link: http://stackoverflow.com/questions/21183328/how-to-make-my-app-a-device-owner/26839548#26839548

I have done something similar, but I have never set system as the owner of my file. I think this was it.
After rebooting my app was device_owner. Hope this will help someone! @pliska87 , let me know!
bit thanks also to @ming030890  and everyone!

**Comment by akashpathak** [comment]
@commonod and @ming030890 the solution by commonod suggests that the only way to fix the problem is by rooting the device. But is there a way to fix this issue without rooting? I thought the Device owner is a standard api introduced by google 5.0 and later.
Is there a way to remove the hidden account?

**Comment by commonod** [comment]
hello @akashpathak I think you are right, it should work without rooting, but unfortunately it doesn't. Maybe it works with plain android...
as I said, I removed the account by rooting my device, not sure if this answers your question

**Comment by ming030890** [comment]
Unfortunately, for those devices that preloaded account can't use set-device-owner, you need to find a device that having no prealoaded account for development.

But it should be fine for proper DO setup (DO setup in production), because we won't have the account checking for it.
You can check all kinds of proper DO setup here:
https://developers.google.com/android/work/prov-devices


Thanks
