### ISSUE TITLE
Application restrictions issues

### ISSUE THREAD

**Issue by ain-is** [googlesamples/android-testdpc#20]
During application restrictions testing I have found several issues in latest 3.0.11 version:
1. andorid:restrictionType="choice" is not supported. Choice restriction is displayed just as string restriction. Data provided by application using android:entries and android:entryValues are ignored.

2. If application defines complex restrictions using andorid:restrictionType="bundle_array" with several different settings inside each bundle, then string restrictions are not handled properly. String restrictions inside bundle are displayed as boolean and default values are ignored.

3. Restrictions are displayed in some random order. Not is order defined by application.

**Comment by theDarkerHorse** [comment]
There is an update to (2) . Please refer to Issue #38

**Comment by mbiebl** [comment]
Still an issue with 6.1.2

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
