### ISSUE TITLE
Cross profile calendar not working properly 

### ISSUE THREAD

**Issue by jtromo** [googlesamples/android-testdpc#201]
I have testdpc set up as a profile and the cross-profile calendar doesn't appear to be working properly.

The option is enabled:

![Screenshot_20240220-071047](https://github.com/googlesamples/android-testdpc/assets/1612439/568dc788-dd03-4ee3-a271-b00b63ae91da)

But doesn't appear to function properly:

![Screenshot_20240220-071021](https://github.com/googlesamples/android-testdpc/assets/1612439/739236bc-a275-4b62-b67d-82f0807cfe13)

**Comment by pfmaggi** [comment]
You control the flag in the App's Settings with the "Enabled cross profile apps" in TestDPC.  
To enable Google's Calendar to share data between the personal and work profile you have to add the `com.google.android.calendar` package name.

![Screenshot_20240320_152148](https://github.com/googlesamples/android-testdpc/assets/188886/3711f150-f6db-4bea-8607-80ee64301738)
