### ISSUE TITLE
cannot import this project to my android studio even after loading bazel plugins

### ISSUE THREAD

**Issue by srinuu7878** [googlesamples/android-testdpc#202]
cannot import this project to my android studio even after loading bazel plugins, can someone please help me on this,

**Comment by pfmaggi** [comment]
I've added some notes on [how to import this project in Android Studio][1].

[1]: https://github.com/googlesamples/android-testdpc/tree/v9.0.6?tab=readme-ov-file#android-studio-import

**Comment by dev-rebootr** [comment]
Unable to open project in android stuio after following the notes. No progress after selecting project views.
