### ISSUE TITLE
TesDPC keeps stopping after Reboot in Android 14

### ISSUE THREAD

**Issue by DummyTestDevice** [googlesamples/android-testdpc#208]
Crash is occurring after Reboot.
Below logs are for reference.

Might need to add foreground service type in Manifest for ResetPasswordService

04-08 13:47:42.147 10315  9694  9694 E AndroidRuntime: FATAL EXCEPTION: main

04-08 13:47:42.147 10315  9694  9694 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 9694

04-08 13:47:42.147 10315  9694  9694 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.afwsamples.testdpc.policy.resetpassword.ResetPasswordService@d62ebdd with Intent { act=android.intent.action.LOCKED_BOOT_COMPLETED cmp=com.afwsamples.testdpc/.policy.resetpassword.ResetPasswordService }: java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{2e4f1ba 9694:com.afwsamples.testdpc/u0a315} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 

04-08 13:47:42.147 10315  9694  9694 E AndroidRuntime:         at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5287)

04-08 13:47:42.147 10315  9694  9694 E AndroidRuntime:         at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)

**Comment by pfmaggi** [comment]
TestDPC v9.0.9 available on the Play store fixes this issue. I'll update the repository on github with the fix as soon as possible.
