### ISSUE TITLE
Screen text not visible properly

### ISSUE THREAD

**Issue by test404386** [googlesamples/android-testdpc#210]
While creating managed account in foldable device in unfolded mode the test in finish setup screen has been cut and not visible properly

Device: Samsung galaxy foldable 5 China region

Test dpc version 9.0.6
Old test dpc version doest have this issue 
Old version 8.0.1
![Uploading 20240422_150942.jpg…]()

**Comment by pfmaggi** [comment]
Hi, can you please upload an image of the issue and a step by step reproduction of the issue?

**Comment by pfmaggi** [comment]
closing as not enough information to reproduce the issue
