### ISSUE TITLE
Issue while running bazel //:testdpc

### ISSUE THREAD

**Issue by ravish21** [googlesamples/android-testdpc#211]
bazel run --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --build_event_binary_file=/var/folders/9v/_2shz0_953x2fkhndbwj46gc0000gp/T/intellij-bep-ed79a29d-91e4-4657-b15f-01e32ff0e5b7 --nobuild_event_binary_file_path_conversion -- //:testdpc
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
ERROR: Cannot run target //:testdpc: Not executable
INFO: Elapsed time: 0.050s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
FAILED: 
ERROR: Build failed. Not running target
INFO: Build Event Protocol files produced successfully.

**Comment by pfmaggi** [comment]
Can you test build TestDPC apk with the included `build.sh` script?

If you have issues with bazel, please check [bazel's documentation][1] and verify that you can correctly run [bazel's Android tutorial][2].

[1]: https://bazel.build/docs/bazel-and-android
[2]: https://bazel.build/start/android-app
