### ISSUE TITLE
After successfully import, bazel sync has some error

### ISSUE THREAD

**Issue by theshubhampanchal** [googlesamples/android-testdpc#213]
OS : Windows 11
Bazel  :  7.1.1
Java : 11.0.23

>gcc --version
gcc (Rev3, Built by MSYS2 project) 13.2.0

>g++ --version
g++ (Rev3, Built by MSYS2 project) 13.2.0

>gdb --version
GNU gdb (GDB) 14.1

Error:An error occurred during the fetch of repository 'bazel_tools~cc_configure_extension~local_config_cc':
Error:<builtin>: fetching cc_autoconf rule //:bazel_tools~cc_configure_extension~local_config_cc: Traceback (most recent call last):
Error:no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:334:10: @@bazel_tools//tools/android:aar_embedded_jars_extractor depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:267:10: @@bazel_tools//tools/android:build_incremental_dexmanifest depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:314:10: @@bazel_tools//tools/android:stubify_manifest depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:283:10: @@bazel_tools//tools/android:incremental_install depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:292:10: @@bazel_tools//tools/android:strip_resources depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/cpp/BUILD:60:19: @@bazel_tools//tools/cpp:optional_current_cc_toolchain depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:356:10: @@bazel_tools//tools/android:resource_extractor depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/cpp/BUILD:58:19: @@bazel_tools//tools/cpp:current_cc_toolchain depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:345:10: @@bazel_tools//tools/android:aar_resources_extractor depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:301:10: @@bazel_tools//tools/android:aar_native_libs_zip_creator depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:274:10: @@bazel_tools//tools/android:build_split_manifest depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/jdk/BUILD:133:10: @@bazel_tools//tools/jdk:proguard_whitelister depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:323:10: @@bazel_tools//tools/android:aar_embedded_proguard_extractor depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/idlclass/BUILD:3:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/idlclass:IdlClass depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/desugar/scan/BUILD:1:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/desugar/scan:KeepScanner depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:41:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:DexFileSplitter depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:23:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android:ZipFilterAction depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/androidsdk/BUILD.bazel:13:25: @@androidsdk//:generate_main_dex_list depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/androidsdk/BUILD.bazel:13:25: @@androidsdk//:d8_compat_dx depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:43:12: @@bazel_tools//tools/android:d8_dexbuilder depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:248:12: @@bazel_tools//tools/android:dexer depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/androidsdk/BUILD.bazel:13:25: @@androidsdk//:apksigner depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:8:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android:ResourceProcessorBusyBox depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/jar/BUILD:3:12: @@rules_jvm_external//private/tools/java/com/github/bazelbuild/rules_jvm_external/jar:AddJarManifestEntry depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:404:12: @@bazel_tools//tools/android:databinding_exec depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/tools/android/BUILD:90:12: @@bazel_tools//tools/android:d8_dexmerger depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:3:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/ziputils:mapper depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD:8:12: @@bazel_tools//src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps:ImportDepsChecker_embedded depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/r8/BUILD:33:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/r8:desugar depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/rules_java~~toolchains~remote_java_tools/BUILD:581:12: @@rules_java~~toolchains~remote_java_tools//:proguard depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/_bazel_shubham/k7j5o23l/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:11:12: @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/ziputils:reducer depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:C:/users/shubham/desktop/emi/android-testdpc-master/android-testdpc-master/BUILD:65:15: //:testdpc depends on @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-x64_windows in repository @@bazel_tools~cc_configure_extension~local_config_cc which failed to fetch. no such package '@@bazel_tools~cc_configure_extension~local_config_cc//': 
Error:command succeeded, but there were loading phase errors
Error:Build did NOT complete successfully

**Comment by gabixyz** [comment]
Hi, have you managed to fix the error? Facing the same or similar currently.

**Comment by pfmaggi** [comment]
Can you test build TestDPC apk with the included build.sh script?

If you have issues with bazel, please check [bazel's documentation](https://bazel.build/docs/bazel-and-android) and verify that you can correctly run [bazel's Android tutorial](https://bazel.build/start/android-app).
