### ISSUE TITLE
How to allow access to work data from personal apps?

### ISSUE THREAD

**Issue by GrapeJelly** [googlesamples/android-testdpc#217]
Is there a setting that allows me to share something from a work app to a personal app, or to access work files from a personal app? I can't find it in Test DPC.

**Comment by LarveyOfficial** [comment]
Was this ever figured out? Still trying to understand how to do this?

**Comment by LarveyOfficial** [comment]
@GrapeJelly have you been able to figure this out? It's the one problem I seem to be having.

**Comment by GrapeJelly** [comment]
@LarveyOfficial No, I didn't find a fix for this issue

**Comment by LarveyOfficial** [comment]
@GrapeJelly Darn. That's a bummer. I ended up getting a copy to clipboard app that shows up in the share page, which allows me to copy anything to my clipboard to then share using my regular account since clipboards are synced.

**Comment by GrapeJelly** [comment]
@LarveyOfficial What app is that? It sounds like a good workaround.

**Comment by LarveyOfficial** [comment]
https://play.google.com/store/apps/details?id=com.slash.clipboard

**Comment by pfmaggi** [comment]
Please review the codelab: ["Build an app that runs on a work profile"](https://developer.android.com/codelabs/work-profile-apps#0) for information on how to implement this feature in your application.

I'm going to close this issue as this is not a TestDPC bug.
