### ISSUE TITLE
Fail to add account.

### ISSUE THREAD

**Issue by RickYang0415** [googlesamples/android-testdpc#22]
Fail to add account after create profile, it will appear "Authenticatorexception: bind failure".

**Comment by ming030890** [comment]
Halo

Would you mind attaching a bug report?

Thanks

**Comment by RickYang0415** [comment]
Attach bug report
[bugreport.zip](https://github.com/googlesamples/android-testdpc/files/665385/bugreport.zip)

**Comment by ming030890** [comment]
Thanks!
However, it seems that it is not a full bugreport, please run adb bugreport to generate a full one.

**Comment by victorchanghk** [comment]
@RickYang0415 Can you always reproduce the issue? What is the account? Is it a GSuite account?

**Comment by victorchanghk** [comment]
Also, it's probably not TestDPC bug. If you can't add Google account, can you report the bug at https://connect.googleforwork.com/login.jspa instead?

**Comment by RickYang0415** [comment]
@victorchanghk Yes, I can always reproduce this issue. It's pop add fail message after I select "add account" radio button and tap next, it even didn't show enter account screen.
My step:
1. Start TestDPC
2. Add work profile
3. Select add account radio button and tap next
4. Pop "Fail to add account" message

**Comment by RickYang0415** [comment]
@ming030890 Add bug report again, it's all.
[bugreport.zip](https://github.com/googlesamples/android-testdpc/files/667817/bugreport.zip)
![screenshot_20161222-015154](https://cloud.githubusercontent.com/assets/18566232/21412689/2510dd1e-c82d-11e6-89ce-a26f85f4dd07.png)

**Comment by RickYang0415** [comment]
![screenshot_20161222-0151541](https://cloud.githubusercontent.com/assets/18566232/21412936/d60005a4-c82e-11e6-8d89-d6f0c9c65441.png)

**Comment by ming030890** [comment]
Thanks for the bugreport.
A bug is created to track internally. Will update you once we have some results.

**Comment by victorchanghk** [comment]
@RickYang0415 
Seems you have modified the source of TestDPC. 

From the log, dpc call AccountManager.addAccountExplicitly in AddAccountActivity. It's different from the [original AddAccountActivity in master branch](https://github.com/googlesamples/android-testdpc/blob/master/app/src/main/java/com/afwsamples/testdpc/AddAccountActivity.java). 

`
12-07 06:29:17.966 29761 29761 E AndroidRuntime: FATAL EXCEPTION: main
12-07 06:29:17.966 29761 29761 E AndroidRuntime: Process: company.rick.cipherlabdpc, PID: 29761
12-07 06:29:17.966 29761 29761 E AndroidRuntime: java.lang.SecurityException: uid 2810097 cannot explicitly add accounts of type: com.google
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1599)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1552)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:890)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:712)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at company.rick.cipherlabdpc.AddAccountActivity.AddAccount(AddAccountActivity.java:70)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at company.rick.cipherlabdpc.AddAccountActivity$1.onClick(AddAccountActivity.java:41)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.view.View.performClick(View.java:5265)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21534)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:815)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5728)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
12-07 06:29:17.966 29761 29761 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

It's expected that AccountManager.addAccountExplicitly fails, as Google Play Services doesn't allow you to do it normally.

Could you reproduce the issue with [the release version of TestDPC](https://play.google.com/store/apps/details?id=com.afwsamples.testdpc&hl=en), and send us bugreport again?

**Comment by RickYang0415** [comment]
@victorchanghk I reproduced the issue used TestDPC from play store, you can check log in this one.
Thanks.
https://github.com/googlesamples/android-testdpc/files/667817/bugreport.zip

**Comment by RickYang0415** [comment]
[bugreport.zip](https://github.com/googlesamples/android-testdpc/files/676568/bugreport.zip) 
Upload bug report again and I found some error message in log.

12-29 03:42:01.182 32398 32398 E AddAccountActivity: addAccount - failed

12-29 03:42:01.182 32398 32398 E AddAccountActivity: android.accounts.AuthenticatorException: bind failure

12-29 03:42:01.182 32398 32398 E AddAccountActivity: 	at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2150)

12-29 03:42:01.182 32398 32398 E AddAccountActivity: 	at android.accounts.AccountManager.-wrap0(AccountManager.java)

12-29 03:42:01.182 32398 32398 E AddAccountActivity: 	at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:1993)

12-29 03:42:01.182 32398 32398 E AddAccountActivity: 	at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)

12-29 03:42:01.182 32398 32398 E AddAccountActivity: 	at android.os.Binder.execTransact(Binder.java:458)

**Comment by ming030890** [comment]
After taking a look of your bugreport, it is because google play service is not enabled in managed profile.
I think you are an OEM?
Please modify vendor_required_apps_managed_profile.xml  and include these two lines
        <item>com.android.vending</item> 
        <item>com.google.android.gms</item>

**Comment by RickYang0415** [comment]
@ming030890 I'll try modify xml file and run again, thanks a lot.

**Comment by ming030890** [comment]
Hey @RickYang0415 

Any update on it? Are you comfortable to have this issue closed? :)

Thanks

**Comment by RickYang0415** [comment]
Hi @ming030890, it can add account normally after I modified the xml file.
Many thanks your help.

**Comment by Reed97123** [comment]
I have the same issue.  I think I need the same solution, editing the xml file.  However, I'm using LineageOS and I don't see the file in existence anywhere.

I see it's supposed to live here:
packages/apps/ManagedProvisioning/res/values/vendor_required_apps_managed_profile.xml

But that doesn't exist, the only directories that are close are these:
/data/misc/profiles/cur/0/com.android.managedprovisioning
/data/misc/profiles/ref/com.android.managedprovisioning
/data/data/com.android.managedprovisioning
/data/user_de/0/com.android.managedprovisioning

But none had any other similarities or the xml file mentioned above.  I'd be very appreciative of any help on how I'm supposed to create or locate that file.  Thanks!
