### ISSUE TITLE
Factory Reset Protection doesn't work at all

### ISSUE THREAD

**Issue by RBWare** [googlesamples/android-testdpc#230]
Process to replicate the issue.

- First boot of Factory Reset device. Skip all steps in the Setup Wizard, except for WiFi connection (no pin, no google account, etc.)
- Open Settings, enable developer settings, and physically connect device to PC.
- `adb install TestDPC_9.0.12.apk`
- `adb shell dpm set-device-owner "com.afwsamples.testdpc/.DeviceAdminReceiver"`
- Launch TestDPC app. Allow Notifications.
- Scroll to "Device owner management" section. Select "Set factory reset protection policy".
- Add the account id being used for the test. Switch, "Enabled" to "Enabled". Select "Save".
- `adb reboot recovery`
- Press power-button + volume up to activate the menu. Use the volume buttons to scroll down to "Wipe Data/Factory Reset" and press the power button to confirm.
- See device data get wiped.
- Reboot the device.
- Notice that no FRP lock is present in the notification bar.
- Move through the setup wizard unhindered, without ever being required to include the FRP credentials associated with the account id used in previous steps.

Performing these same steps on an Android 14 device, shows the lock in the notification bar and the credentials are required during setup wizard. On Android 15, it's completely ignored and users are free to complete setup wizard however they want to.

**Comment by LAKSHAYNE** [comment]
With me i am not able to get in the lock is set with the mail id i provided but i am not able to log in lack into it using that . It says signin with the device owner's mail id . 😢
