### ISSUE TITLE
ADB command to remove DO.

### ISSUE THREAD

**Issue by raiavancini** [googlesamples/android-testdpc#24]
Hello,

I am aware that using the following command I am able to set the application as a DO.
-> adb shell dpm set-device-owner "com.afwsamples.testdpc/.DeviceAdminReceiver"

There is anyway to revert it, i.e. remove the DO from the device with an ADB command?
After setting the DO I can't remove the active admin from the app.
For now I'm doing a factory reset everytime I need to remove the DO, and it takes a long time.

Thanks!

**Comment by ming030890** [comment]
You can use adb shell dpm remove-active-admin to remove device owner package that declared android:testOnly="true" in manifest.

Or you can add a backdoor button which triggers DevicePolicyManager.clearDeviceOwnerApp.

**Comment by raiavancini** [comment]
Ok, thanks!
