### ISSUE TITLE
Poweroff the device in kiosk mode

### ISSUE THREAD

**Issue by lOlIl** [googlesamples/android-testdpc#25]
After setting apps into kiosk mode, it is impossible to turn off the device.
Is it bug or feature? Thanks for any advice.

The device:
LG K8 with Android 6.0

I am getting this exception:

> AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
>                                                    java.lang.SecurityException: Invalid uid, expected 0 callingUid=1000 effectiveUid=10093
>                                                        at com.android.server.am.ActivityManagerService.stopLockTaskMode(ActivityManagerService.java:9599)
>                                                        at com.android.server.power.ShutdownThreadAO.ajc$before$com_android_server_power_ShutdownThreadAO$4$eb262cff(ShutdownThreadAO.java:396)
>                                                        at com.android.server.power.ShutdownThread.beginShutdownSequence(ShutdownThread.java:373)
>                                                        at com.android.server.power.ShutdownThread.ajc$privMethod$com_android_server_power_ShutdownThreadAO$com_android_server_power_ShutdownThread$beginShutdownSequence(ShutdownThread.java:1)
>                                                        at com.android.server.power.ShutdownThreadAO.ajc$around$com_android_server_power_ShutdownThreadAO$2$503f8934(ShutdownThreadAO.java:360)
>                                                        at com.android.server.power.ShutdownThread.shutdownInner(ShutdownThread.java:146)
>                                                        at com.android.server.power.ShutdownThread.reboot(ShutdownThread.java:239)
>                                                        at com.android.server.policy.LGGlobalActions$9.onClick(LGGlobalActions.java:392)
>                                                        at android.view.View.performClick(View.java:5210)
>                                                        at android.view.View$PerformClick.run(View.java:21328)
>                                                        at android.os.Handler.handleCallback(Handler.java:739)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                        at android.os.Looper.loop(Looper.java:148)
>                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
>                                                        at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by ming030890** [comment]
It is definitely not expected behavior and it is likely a LG specific issue.

**Comment by hex539** [comment]
@ming030890 this seems like something we should be testing with CTS in that case to make sure all devices targeting a certain release have consistent behaviour (either turn off / don't turn off depending on the intent here, looks like the intent is to allow power off).

Do you agree?

**Comment by ming030890** [comment]
@lOlIl Thanks for reporting the bug, it is now tracked internally and we will try to contact LG.
In the meanwhile, please find another device to test your project.

Re @hex539  Ya, make sense, tracked internally.
