### ISSUE TITLE
Test on emulator

### ISSUE THREAD

**Issue by about-midnight** [googlesamples/android-testdpc#27]
During the setup I get this message
![screenshot_20170315_113633](https://cloud.githubusercontent.com/assets/1573101/23939904/dcd89e5a-0973-11e7-98f3-201aba9ff985.png)

And the emulator encryption does not seem to be working. Is there a workaround?

**Comment by ming030890** [comment]
Try this:

adb root
adb shell setprop persist.sys.no_req_encrypt true
And restart TestDPC and try provisioning again.

Also, which image are you using? I believe you won't see this in N+ images as encryption is come in the first place.

Thanks
