### ISSUE TITLE
Fatal exception is occurred by getRequiredStrongAuthTimeout()

### ISSUE THREAD

**Issue by dsdlsu** [googlesamples/android-testdpc#28]
I have found an issue which is occurred when I try to enter the "Lock screen restrictions" menu in TestDPC 4.0
The issue is only happened at below conditions.
Device : Android 7.0
TestDPC : 4.0

03-29 11:26:52.922  5751  5751 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 5751
03-29 11:26:52.922  5751  5751 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getRequiredStrongAuthTimeout(Landroid/content/ComponentName;)J in class Landroid/app/admin/DevicePolicyManager; or its super classes (declaration of 'android.app.admin.DevicePolicyManager' appears in /system/framework/framework.jar)
03-29 11:26:52.922  5751  5751 E AndroidRuntime:    at com.afwsamples.testdpc.policy.keyguard.LockScreenPolicyFragment.setupAll(Unknown Source)
03-29 11:26:52.922  5751  5751 E AndroidRuntime:    at com.afwsamples.testdpc.policy.keyguard.LockScreenPolicyFragment.onCreatePreferences(Unknown Source)
03-29 11:26:52.922  5751  5751 E AndroidRuntime:    at android.support.v14.preference.PreferenceFragment.onCreate(Unknown Source)

As for above logs, it points out getRequiredStrongAuthTimeout()
Among many changes between 7.0 and 7.1, getRequiredStrongAuthTimeout() is one of them.
As the function is added from 7.1, all of the devices with version 7.0 maybe have the same issue.
Please check the issue.

Thank you.

**Comment by ming030890** [comment]
Thanks for reporting, it is fixed internally.
