### ISSUE TITLE
Set status bar icons visible

### ISSUE THREAD

**Issue by No1e** [googlesamples/android-testdpc#29]
"Kiosk Mode" is very nice feature especially how it can be implemented in Android 6, but there is one thing that is nor very nice. Entering lock task mode makes status bar icons invisible (including battery status and wireless status).

"Kiosk Mode" is normally used on company owned devices, often industrial Android base devices from different vendors (Honeywell, Zebra, ...), where user is allowed to use single application or only restricted set of applications. User often work off their desks (e.g. warehouse...).  Since user productivity depends of health of device, it is essential to have those icons back since users has to know when there is a problem with wireless, and especially what is the status of battery so they can schedule battery recharge or replace. Those devices are not like user consumer mobile devices where you can plug in charger and use it even when device is on the charger (making calls etc.).

1. What is the reason behind decision to hide all status bar icons in "lock task" mode?
2. Is there a way to set status bar icons visible in "lock task" mode?

**Comment by jeremywizy** [comment]
Hi No1e, 

From my understanding, StartLockTask (Kiosk Mode) lock the device on the current Activity, and restrict access to anything else. The top status bar is the top menu and is hidden too.

I faced this issue too, and create my own "Status app", whitelisted for Kiosk Mode (and thus accessible for end user) and display all the information I want (battery level, data consumtion...)

**Comment by No1e** [comment]
Hi Jeremy,

It seems that we are not the only ones that have this problem, but I have not found that there is really support in Android API to enable this. I noticed couple of other problems in the current features list of DPC/Lock Task mode ...

Well, its a bit more complex than what you described, depending if your app is device owner or not...

In my case, I have admin app that is device owner and has the following features:
- Device owner. Entering in "lock task" mode in this app will disable some stuff (status bar, hide recent apps/home buttons, disable back button when in activity from this app). 
- Main launcher activity (it overtakes google launcher responsibility)
- Disables google search (some devices have hardware google search button)
- Maintains apps that are allowed to use "lock task" mode
- Originally "screen lock" (timeout, button) is also disabled when activity from device owner app enters lock task mode, this is a security issue, so I had to do some hack in order to enable this.
- Starting allowed apps. In this case home/recent buttons are still disabled, but back button is not, allowing to get back to previous activity (the one from where we can start other apps). 
- etc. 

I have workaround to include foreground service in my admin app, This service will create "custom" status bar (draw over other apps) and put there notifications that I need. But, I would like to avoid this if possible by using Android API to save battery that will be used for those activities.

**Comment by ming030890** [comment]
Thanks for the suggestion.
The feature request is now tracked internally.

**Comment by ming030890** [comment]
Closing, and stay tuned :)

Thanks

**Comment by namputo** [comment]
Hi is it possible to unhide the home and recents button while still in the locktask mode. I  understand they are disabled, and that is okay

**Comment by No1e** [comment]
Nope.
Sent from my Windows 10 phone

**Comment by yungtravla** [comment]
As of Android 9 this has become possible using `dpm.setLockTaskFeatures()` function.

The status bar can be shown whilst in lockTask mode like so:

```
devicePolicyManager.setLockTaskFeatures(adminComponentName, DevicePolicyManager.LOCK_TASK_FEATURE_SYSTEM_INFO);
```

From the Android docs:

>  LOCK_TASK_FEATURE_SYSTEM_INFO
>
> Enables the status bar’s system info area that contains indicators such as connectivity, battery, and sound and vibrate options.

https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setLockTaskFeatures(android.content.ComponentName,%20int)

**Comment by KuznetsovS** [comment]
Is it possible to only show status bar, like in Android 7?
