### ISSUE TITLE
minSdkVersion not working, cannot install on older devices

### ISSUE THREAD

**Issue by shizhx** [googlesamples/android-testdpc#31]
because android-O sdk can only works on Android Studio 3.0, I use Android Studio 3.0 to build the project.
but I cannot install the app on pre-O devices even I choose target25 productFlavor, Android Studio tell me that minSdkVersion is 25 preview-O.

**Comment by ming030890** [comment]
Could you try the command line way?
/gradlew assembleDebug
adb install -r out/gradle/TestDPC/build/outputs/apk/TestDPC-target25-debug.apk

Thanks

**Comment by shizhx** [comment]
@ming030890 still not works
```
➜  android-testdpc git:(work) adb install -r app/build/outputs/apk/TestDPC-target25-debug.apk
app/build/outputs/apk/TestDPC-target25-debug.apk: 1 file pushed. 7.0 MB/s (3572301 bytes in 0.488s)
	pkg: /data/local/tmp/TestDPC-target25-debug.apk
Failure [INSTALL_FAILED_OLDER_SDK]
```
