### ISSUE TITLE
INSTALL_FAILED_TEST_ONLY

### ISSUE THREAD

**Issue by dj-4war** [googlesamples/android-testdpc#32]
With the latest source I am not able to test NFC bump, always failing with the "Not able to setup Rest" on factory rest mode. 

I tried installing the APK to see what could be the issue. Here is the issue when I trigger through terminal .
**Failure [INSTALL_FAILED_TEST_ONLY]**

Seems issue with the alpha gradle will not allow with the other than test mode. 

Here is the gradle 

  dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

I tried with the Signed APK still the problem exists. 

Sooner response is appreciated.

**Comment by ming030890** [comment]
There are two build flavors in the latest source, one targeting N and one targeting O.
Please use the N one for testing NFC bump.

Thanks.

**Comment by petarov** [comment]
I have a somewhat similar issue. I did several modifications and tried to produce a signed N build and upload the APK as an alpha version in PlayStore. In PlayStore I then get:

`You cannot upload a test-only APK`

I'm trying to update the build gradle files atm to use gradle-2.3.2, but I face bunch of other issues. Could it be that `3.0.0-alpha1` prevents publishing an APKs to Alpha?

**Comment by ming030890** [comment]
When you run ./gradlew assembleDebug, you should find two apks are built. Could you try again with the one targeting N please?
 Thanks

**Comment by petarov** [comment]
Thanks for the feedback, but sadly it's still the same. I ran `assembleRelease` from the command line and then tried to upload the APK - `target25/myapp-target25-release.apk`.

![screen shot 2017-05-24 at 18 12 24](https://cloud.githubusercontent.com/assets/547597/26413554/a89a1e82-40ac-11e7-9366-78594df2b4b0.png)

**Comment by dj-4war** [comment]
@ming030890 I have generated signed **target 25** build and tried still the same issue.

**Comment by ming030890** [comment]
I can reproduce the same issue in my side.
I guess it is related to O-preview SDK rather than the gradle plugin, and it may be the measure to avoid developers releasing apps build against preview SDK.

**Comment by ming030890** [comment]
@dj-4war 

Are you intend to test NFC bump? Or do you just want to set testdpc as device owner?
If it is the latter case, you can use command set-device-owner to workaround this.

**Comment by dj-4war** [comment]
@ming030890 : Yes I want to test NFC bump because I need Device Owner, want to see the newer APIs and provision process. So I need NFC Bump.

**Comment by ming030890** [comment]
@dj-4war 

You can run this command to set testdpc as device owner without NFC bump.
adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver

Hope it can workaround your issue.

**Comment by dj-4war** [comment]
Thanks for the link, can I know what is the issue for this ?.. 

I don't see **testOnly="false"** anywhere in the app, is it O libs ?

**Comment by ming030890** [comment]
From my understanding, it is the build system who adds the testOnly="true" when it sees you are compiling against the O preview SDK, in order to stop you from uploading this APK to play until the SDK is finalized.

In theory, you can use some hack to remove the testOnly = true. 
It is an example:
https://stackoverflow.com/questions/35929484/android-n-cannot-run-on-lower-api-though-minsdk-set-to-14

**Comment by dj-4war** [comment]
If that is the case they the build system would have allow for target 25 at least.  BTW in the above context build system meaning gradle or Android core?. 
Were you able to build target 25 flavor and install with the install trigger?

**Comment by petarov** [comment]
Just wanted to add that, as expected, installing target25 via **adb** didn't work for me either.

```
	pkg: /data/local/tmp/mayapp-target25-release.apk
Failure [INSTALL_FAILED_TEST_ONLY]
```

Atm, I use the [3.0.11](https://github.com/googlesamples/android-testdpc/releases/tag/3.0.11) branch to build, test & upload. That works nicely. 

Once SDK 26.0 is out, I'll try the master branch again.

**Comment by dj-4war** [comment]
Thanks, seems it is updated very long **Aug 12, 2016**

**Comment by ming030890** [comment]
It should be working now, thanks

**Comment by liuwenping828** [comment]
$ adb shell pm install -t -r "/data/local/tmp/com.test.record"
	pkg: /data/local/tmp/com.test.record
Failure [INSTALL_FAILED_TEST_ONLY]


$ adb shell pm uninstall com.test.record
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APK

**Comment by anilsakr** [comment]
It worked for me. Try to run this and build again. ./gradlew assembleRelease

Maybe You are uploading the wrong apk file which is generated previously not the signed apk. So select the apk file by locating the exact path of the generated signed apk file.
