### ISSUE TITLE
Device Owner provision 

### ISSUE THREAD

**Issue by dj-4war** [googlesamples/android-testdpc#33]
I am looking for Device Owner provision without NFC bump. 

I see from documentation that there are only 2 ways to get into the Device Owner mode. 
1. NFC bump 
2. Google Cloud 

NFC bump is pretty much straight forward, would like to know more about Google Cloud Provision process, where no where it mentioned clearly in the documentation. If some one could give us the steps to start with that would really help us to get into the our product.
@ming030890  If you have some inputs on it appreciate your help.

**Comment by ming030890** [comment]
We have more ways to kick start device owner provisioning.
Please check this for details.
https://developers.google.com/android/work/prov-devices

And to register the cloud provisioning process, please check this one:
https://developers.google.com/android/work/register

**Comment by dj-4war** [comment]
Thanks for the response, I have gone trough above documentation. I am missing the how does the device gets into Device Owner mode if the device does not have NFC, it says Google Cloud, I need bit more explanation in this area. 

Appreciate if you could give me the steps involved in this cycle.

**Comment by ming030890** [comment]
@dj-4war It is mentioned in the doc :)
Please find "Key provisioning differences across Android versions", for example, you can use QR code in 7.0+.

**Comment by ming030890** [comment]
Oh, there is a direct link to that section.
https://developers.google.com/android/work/prov-devices#Key_provisioning_differences_across_android_releases

Assume you have found the bit, closing.
Thanks
