### ISSUE TITLE
Build failed on Android Studio 3.0 alpha 5

### ISSUE THREAD

**Issue by oasisfeng** [googlesamples/android-testdpc#36]
`Gradle sync failed: java.lang.AssertionError: ':setup-wizard-lib-platform-release:@aar' is not a valid maven coordinate.`

It builds correctly on AS alpha 4, but fails on alpha 5. Seems like the local AAR dependency syntax causes trouble here.

**Comment by markwhitaker** [comment]
Same problem here. Thanks for the info on alpha 4, I'll try falling back to that for now.

**Comment by oasisfeng** [comment]
Seems like fixed in upcoming Android Studio release: https://issuetracker.google.com/issues/63232245

**Comment by markwhitaker** [comment]
Works fine again in alpha 6.

**Comment by ming030890** [comment]
Thanks for reporting and confirming the fix.
