### ISSUE TITLE
This app is not an admin

### ISSUE THREAD

**Issue by guocs** [googlesamples/android-testdpc#38]
I want to test work profile function.

Android version: 5.1
Mobile phone: Huawei Mate 7

After setup managed profile,  to run Test DPC(baged). It shows  "This app is not an admin" .  why ? thanks!

**Comment by sarog** [comment]
You need to do the following after installing TestDPC:

1. Make `TestDPC` an Administrator in your device's Settings -> Security screen.
2. Run the following `adb` command to make TestDPC a Device Owner:
``adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver``
3. Launch TestDPC and configure policies as you please.

**Comment by ming030890** [comment]
Could you capture a bugreport (adb bugreport) and attach it to here? This will help us to take a look of the issue.
Thanks

**Comment by milhauscz** [comment]
Note: this bug does not occur in the 3.0.11 version of the app - [see the video](https://www.youtube.com/watch?v=cBu0PjzxVnU).

**Comment by ming030890** [comment]
Re milhauscz, I think you are referring a different issue.
You should see two TestDPC icons in launcher, tap on "Set up" TestDPC one, and then follow on-screen instructions. We have realized this UX is not good and would tune it in next version.

Thanks.
