### ISSUE TITLE
This Gradle plugin requires Studio 3.0 minimum

### ISSUE THREAD

**Issue by eliotstock** [googlesamples/android-testdpc#39]
As of July 2017, this project doesn't build with Android Studio 2.3.3.

_Gradle 'android-testdpc' project refresh failed
Error:This Gradle plugin requires Studio 3.0 minimum_

If we need to change the update channel for AS, this should be mentioned in the README.md.

**Comment by StrawHatAaron** [comment]
I have the same problem

**Comment by vikas0** [comment]
Error:This Gradle plugin requires Studio 3.0 minimum

**Comment by vikas0** [comment]
@eliotstock @StrawHatAaron did you guys find any way around. getting the same error.

**Comment by eliotstock** [comment]
I just used Android Studio 3.0. The issue is not that AS 3.0 is required, it's that the `README.md` doesn't mention that.
