### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by amalChandran** [googlesamples/android-testdpc#4]
Is the silent install feature supposed to work in lollypop devices?

If yes, the silent install feature is not working in 5.0 devices. Please get back ASAP.

Thanks.

**Comment by hex539** [comment]
"silent install" as a phrase doesn't match anything in this repo. Are you referring to EnableCosuActivity?

If you'd like to help track the problem down, you can provide reproduction steps and/or take some diagnostics by running [adb bugreport](http://developer.android.com/tools/help/adb.html#commandsummary).

**Comment by amalChandran** [comment]
Under CosuUtils... there is a installPackage function.

I am referring to that as a silent install(Installing without user interaction in the background).

**Comment by ming030890** [comment]
This feature is introduced in M.
Please take a look of "Silent install and uninstall of apps by Device Owner" section in the below url.
https://developer.android.com/about/versions/marshmallow/android-6.0.html

Thanks

**Comment by amalChandran** [comment]
Thanks @ming030890 . You can close this issue.

**Comment by amalChandran** [comment]
Thanks @ming030890 . You can close this issue.
