### ISSUE TITLE
Allow DO create managed profile on O

### ISSUE THREAD

**Issue by legoming** [googlesamples/android-testdpc#41]
According to O API description (as below), DO device can add managed profile now, so what's the purpose of this managed profile?
Is this designed for COPE (Corporate Owned Personal Enabled) mode?
But the profile data is always monitored by DO, right?

https://developer.android.com/reference/android/os/UserManager.html

> DISALLOW_ADD_MANAGED_PROFILE
> added in API level 26
> 
> String DISALLOW_ADD_MANAGED_PROFILE
> 
> Specifies if a user is disallowed from adding managed profiles.
> 
> The default value for an unmanaged user is false. For users with a device owner set, the default is true.
> 
> This restriction has no effect on managed profiles.
> 
> Key for user restrictions.
> 
> Type: Boolean

**Comment by ming030890** [comment]
Basically, yes.

Please check out [this](https://developer.android.com/preview/features/work.html#work-profile-on-managed-devices) for details.
Thanks.

**Comment by ming030890** [comment]
Opps, the link is broken :(

**Comment by legoming** [comment]
@tony-mak is there any instruction about how to setup a work profile in DO device?

**Comment by tony-mak** [comment]
Sorry about the delay, here is the documentation link:
https://developers.google.com/android/work/dpc/work-profile-on-managed-device

@legoming Yes, what you said.
