### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by arvindk90** [googlesamples/android-testdpc#44]
I have changed dependency from Studio 3.0.0 to 2.3.3 but now I am getting the error "Gradle DSL Method not found : 'api()' ".

**Comment by MHHuk** [comment]
I'm getting a screen wich says "oops! This device is locked by factory reset protection" what should i do to fix this error? I've tryed to log in with an incorrect account by error  and it said to me that I should wait 24 hours so I decided to try this app and I got this error any help?
