### ISSUE TITLE
device owner provisioning on device without NFC

### ISSUE THREAD

**Issue by vikas0** [googlesamples/android-testdpc#47]
i am able to Test device owner provisioning on device with adb dpm set-device_owner command, but and i know that in actual practice after the testing is done, the device will be provisioned with a programmer device passing NFC message.
what if the device does not support NFC.

**Comment by jeremywizy** [comment]
Hi vikas0, 

As part of my experience, few devices support NFC enrollment: most of them does not activate NFC in reset factory state.

The best enrollment method is the DPC identifier: ie afw#your_dpc_identifier you specified when the system ask you to prompt the email address.

You have to setup wifi manually, but it ensures the device to be configured correctly as device owner.

One point though: the DPC identifier has to be requested to Google through a form. Need to be partner and it takes few days for validation.

Other method like QR code and Zero Touch are great too but requires android 7.0 and 7.1+
