### ISSUE TITLE
How to install "Test DPC" on an Android 6.0 device without NFC?

### ISSUE THREAD

**Issue by chrisdew** [googlesamples/android-testdpc#48]
What's the easiest way to install the "Test DPC" app on an Android 6.0 tablet, so that it thinks it's a "Device Owner".

I tried installing the app from from Google Play.

It just showed greyed-out options for the Lock Task Mode settings, where I need to add my app to test that it can use this functionality successfully.  

I therefore think that I may need to "provision" the Test DPC app after a factory reset.  (If it works, I write a DPC app for our company.)

Most of the methods are either not available for Android 6.0 or involve writing code to call Google's APIs.

This is for the purpose of testing the Lock Task Mode feature on one device.  I do want to create Enterprise ID's etc. at this stage.

What is the simplest way of installing Test DPC so that it thinks that it is the "device owner"?

**Comment by jeremywizy** [comment]
Hi Chris, 

Provisionning the Test DPC app after a factory reset is the only way to set it as Device Owner.

The DPC identifier method is great, but I don't know if Google provides one for the test DPC.

have you tried the adb command ?
adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver

please refer to [gitHub](https://github.com/googlesamples/android-testdpc)

**Comment by chrisdew** [comment]
Thanks for taking the time to reply.  Even after a factory reset, the adb method suffers from chicken-and-egg syndrome.  How can you allow a PC to connect with adb before it creates a user-acount?

chris@purple:~$ adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device
	at android.os.Parcel.readException(Parcel.java:1691)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:4713)
	at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:148)
	at com.android.commands.dpm.Dpm.onRun(Dpm.java:96)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.dpm.Dpm.main(Dpm.java:41)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:294)

**Comment by GeorgeDewar** [comment]
Hi @chrisdew, I can answer this one. Before you can set a device owner using adb, you must *remove* any accounts on the device (i.e. your Google account). You can add it again afterwards if desired,

The best thing to do is not to add the account during the initial device setup, rather to add it after setting the device owner.

**Comment by chrisdew** [comment]
So I just need to build the Test DPC app myself, then side-load that over adb, rather than using Google Play to download it?

**Comment by GeorgeDewar** [comment]
Yep, that will work. Or, you can install it from the Play Store, remove the
account, set the device owner and then add the account again. That's what
we used to do with our app but if you're doing a lot then it's quicker to
install it via adb first.

**Comment by chrisdew** [comment]
Thanks, removing the Google account let me use `adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver`.
