### ISSUE TITLE
QR-code example: generating SHA1 and SHA-256 base64 encoded checksum issue.

### ISSUE THREAD

**Issue by ppilip** [googlesamples/android-testdpc#49]
Hello everybody,

I'm using your QR-code example and trying to generate exact APK checksum (**gJD2YwtOiWJHkSMkkIfLRlj-quNqG1fb6v100QmzM9w=**) of the APK provided in example QR code http://down-box.appspot.com/qr/nQB0tw7b. I want to make sure I'm doing it the right way for my app.

Anyways, I was not sure if given checksum was generated with SHA1 or SHA-256 so I tried both.

When I tried `cat TestDPC_4005.apk | openssl dgst -binary -sha1 | openssl base64` for **SHA1**
result was

> qimlbnIVNEA2qtWpIr9O2m9O0XE=

When I tried `cat TestDPC_4005.apk | openssl dgst -binary -sha256 | openssl base64` for **SHA256**
result was

> z0KB1LIGCu3T+o7cDGP6Hpo6hNP+OhXjAfl1uWOJFU8=

I even tried some of the online tools for generating these checksums (https://hash.online-convert.com/sha1-generator) and results were the same. I could not get the exact one that was given in example. Is there any step that I'm missing here that was not described in the documentation?

Could you please give example of tool/command you use to generate it or at least some hints of what could go wrong in my case.

Thanks in advance.

**Comment by GeorgeDewar** [comment]
I have the same problem, which I'm trying to solve right now. In the meantime, I wanted to pass on a tip I've discovered (in case you haven't). The UI tries to get you to factory reset the device after the failure, and the documentation states *"If the checksum doesn't match an error will be shown to the user and the user will be asked to factory reset the device."*.

**You do not have to.** You can hold down the power button and simply restart the device. Your WiFi settings will remain and you can carry on testing.

**Comment by GeorgeDewar** [comment]
I'm just going to drop one more (hopefully useful) tip here, which I don't have time to follow up myself right now: The relevant source code to compute and compare the hashes appears to live in https://android.googlesource.com/platform/packages/apps/ManagedProvisioning.

**Comment by jasonbayton** [comment]
Hi folks, 

The checksum has to be URL safe. I wrote about it here: 
https://bayton.org/docs/enterprise-mobility/mobileiron/manual-android-enterprise-work-managed-qr-code-generation-for-mobileiron/#validate-the-checksum

**Comment by GeorgeDewar** [comment]
Thanks @jasonbayton. I've been trying that myself (I had found the same advice in this (StackOverflow post)[https://stackoverflow.com/questions/26509770/checksum-error-while-provisioning-android-lollipop] and thought that'd be it solved) but it still does not work for me (same problem).

I also find it interesting that the example QR code in the OP *does* end with an =. The commands you have do not replicate a code similar to that one - but that one still works. It's quite strange!

**Comment by jasonbayton** [comment]
What you see in the example in the OP (http://down-box.appspot.com/qr/nQB0tw7b) is an admin signature checksum. What you're generating with these commands is a package checksum, they'll be different :)

The signature checksum AFAIK won't change between DPC updates, while the package checksum will. If you'd like to use a package ID checksum instead, replace: 

`"android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM":
"xyzzy",`

with 

`"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM":
"xyzzy",`

**Comment by misko9** [comment]
This post should help you get the v1 signature checksum:
https://stackoverflow.com/questions/44836891/how-do-i-get-the-signature-checksum-of-my-apk

This post describes the v2 signature checksum:
https://stackoverflow.com/questions/44855952/how-do-i-get-the-signature-checksum-of-my-apk-that-is-signed-with-only-the-v2-sc

**Comment by GeorgeDewar** [comment]
@jasonbayton thank you so much! Who knows how much longer it would have taken for me to notice this silly mistake - thanks also @misko9 for the info about the signature checksum.

It is working perfectly for me now.

**Comment by ppilip** [comment]
I managed to get correct
android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM
(with = at the end) of the demo app with following command .

`keytool -list -printcert -jarfile TestDPC_4005.apk | perl -nle "print $& if m{(?<=SHA256:) .*}" | xxd -r -p | openssl base64 | tr -- '+' '-_'`

I used similar command that was provided by first link of @misko9 answer. I modified it a bit (for my macOS config) and it worked. It also worked with my own APK and installation went without any issue.

If you want to make sure there is no '=' in the middle of the checksum string, use this command, but remember to add = at the end (not sure if it can work without it).

`keytool -list -printcert -jarfile [path_to_your_apk] | perl -nle "print $& if m{(?<=SHA256:) .*}" | xxd -r -p | openssl base64 | tr -d '=' | tr -- '+/=' '-_'`

Thanks everyone.

**Comment by astralmaster** [comment]
> What you see in the example in the OP (http://down-box.appspot.com/qr/nQB0tw7b) is an admin signature checksum. What you're generating with these commands is a package checksum, they'll be different :)
> 
> The signature checksum AFAIK won't change between DPC updates, while the package checksum will. If you'd like to use a package ID checksum instead, replace:
> 
> `"android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "xyzzy",`
> 
> with
> 
> `"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM": "xyzzy",`

 I cannot believe I spent the last 15 hours specifying the wrong parameter and never noticed these two are actually different.
