### ISSUE TITLE
Are external USB NFC-readers supported for provisioning Android 6 devices?

### ISSUE THREAD

**Issue by chrisdew** [googlesamples/android-testdpc#50]
Looking at https://developers.google.com/android/work/prov-devices#Key_provisioning_differences_across_android_releases it seems that NFC provisioning is the only available way to provision a DPC app as device owner without using Google accounts.

Are any, some, or all external USB NFC-readers supported for the provisioning process?  (All our devices have a USB host/on-the-go port.)

**Comment by ming030890** [comment]
At the least, we have QR code provisioning as well, please check the readme
page, thanks

**Comment by chrisdew** [comment]
@ming030890 QR code provisioning is not supported for Android 6.0, with which I am stuck.  https://developers.google.com/android/work/prov-devices#Key_provisioning_differences_across_android_releases

**Comment by ming030890** [comment]
Sorry, I overlooked it. We didn't test any external NFC reader before, so I don't really have the answer.
However, the doc identifier does not require a Google account as well. (To be precise, the identifier itself is a fake Google account)

**Comment by chrisdew** [comment]
@ming030890 Sorry, I can't see "doc identifier" on the table "Key provisioning differences across Android versions" on https://developers.google.com/android/work/prov-devices  Ctrl-F on the same page finds nothing for "doc identifier" nor on https://github.com/googlesamples/android-testdpc

Could you give me a link to "doc identifier"?

**Comment by ming030890** [comment]
Typo :) it should be dpc identifier.

**Comment by chrisdew** [comment]
@ming030890 Thanks for your help, but I'll leave the question open in case someone has experience with USB NFC-readers and provisioning.
