### ISSUE TITLE
Long press of back button on "Task Locked" app allows escape.

### ISSUE THREAD

**Issue by chrisdew** [googlesamples/android-testdpc#51]
I have made a trivial app which calls `startLockTask()` and `stopLockTask()` in response to a couple of buttons.

I've added this app to Test DPC's "Lock task" list.

`startLockTask()` displays a "pinned" toast, and removes two soft buttons, leaving just "back".

Pressing "back" results in an "App is pinned: Unpinning isn't allowed on this device." toast.

This is all fine and expected.

If I "long-press" "back" the same toast is displayed, but the "home" and "recent" soft-buttons re-appear and I can escape the trivial app.

Is this "long-press" behaviour just an escape-mechanism for "Test DPC" or is this how `startTaskLock()` works in production (which would make it unsuitable for my use-case).

**Comment by chrisdew** [comment]
Update: The problem occurs on an Asus P00A with Android 7, but does not occur on an Android P00C with Android 6.

**Comment by chrisdew** [comment]
I've also found another developer reporting this issue - it looks like a bug that was introduced after Android 6.  https://stackoverflow.com/questions/32909074/android-stop-back-button-from-exiting-locktask-kiosk-mode/46772644

**Comment by chrisdew** [comment]
Also works correctly on Galaxy XCover 3 phone running 6.0.1.

**Comment by phevans** [comment]
We also have this issue on an Asus tablet. Is the long press on back an Asus "enhancement"?

**Comment by sacot41** [comment]
Same issue with Cat S41 on Nougat...

**Comment by jeremywizy** [comment]
Same issue with Zebra TC75x

**Comment by bfvanrooyen** [comment]
@spiteful1990 Not sure about your code, but I had the same issue and calling startLockTask() in onStart() and onResume() fixed it for me.

**Comment by spiteful1990** [comment]
@bfvanrooyen 
Calling startLockTask() inside onStart() solved the problem.
Thank you very much!!

**Comment by jscott1989** [comment]
Closing old issue.

This appears to be potentially a problem with the lock task API - so if it's still an issue could you open it on the Android issue tracker please? https://source.android.com/setup/contribute/report-bugs
