### ISSUE TITLE
Kiosk Mode, system dialogs

### ISSUE THREAD

**Issue by navinjethani** [googlesamples/android-testdpc#52]
I have written a Kiosk mode application but I want to allow system Dialog (example Bluetooth Pairing Request)
I have enabled SystemApp (com.android.bluetooth), but the Bluetooth Pairing Pin Dialog is not shown.

Any pointers to debug this

**Comment by jscott1989** [comment]
Currently you'd have to allow the settings app (`com.android.settings`) to allow the bluetooth pairing pin dialog****
