### ISSUE TITLE
Force Close when wipe data from Testdpc admin

### ISSUE THREAD

**Issue by ss14** [googlesamples/android-testdpc#55]
Steps to reproduce issue:
1. Create PO from Testdpc
2. Wipe data with "factory rest protection" check

From logs:
SecurityException: Only device owner admins can set WIPE_RESET_PROTECTION_DATA

Fix: disable this option from wipe data dialog if PO admin

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
