### ISSUE TITLE
Setup Testdpc crash

### ISSUE THREAD

**Issue by FJH1** [googlesamples/android-testdpc#58]
I have devices with the same spec and Version of Android 7, only difference is suppose to be
in memory the one model have 2GB memory and the other only 3GB memory.
On the on Setup TestDpc run and finish . On the other-one Setup Testdpc 
Set up manage profile starts then show the Setup Work Profile screen ,the next popus up
"The Exchange Services has been updated Choose what to allow this app to access" , I tab on Continue
and the the app TestDPC dies, and pops back to "Set up managment" Screen
Can someone please advise how to find what the problem can bee ?
I will even pay to get TestPDC to setup a workprofile. 
IF I go to Settings  Apps and list all apps, I can see that Applications were duplicated with the badge icon apps listed, but if I go to Accounts it shows Work Managed by Test DPC, but displays "Work profile isn't available yet.

Any suggestions to find what is causing the problem.
Ho do I find the reason why Setup TestDPC does not complete the process 
Thank You

**Comment by jscott1989** [comment]
Closing old issue - if this is still a problem on the latest version please open a new bug.
