### ISSUE TITLE
API 21 can not install from unknown sources in reality

### ISSUE THREAD

**Issue by shizhx** [googlesamples/android-testdpc#6]
document [TestDPC_UserGuide.pdf](https://github.com/googlesamples/android-testdpc/blob/master/TestDPC_UserGuide.pdf) said that API 21 **CAN** install from unknown sources in `managed-profile` on `9th page`, but in fact, it **CAN NOT**.
becuase the option `Settings.Secure.INSTALL_NON_MARKET_APPS` can not turned on by profile owner until API 22.
code from `DevicePolicyManagerService`:
API 21
```java
    static {
        SECURE_SETTINGS_WHITELIST = new HashSet();
        SECURE_SETTINGS_WHITELIST.add(Settings.Secure.DEFAULT_INPUT_METHOD);
        SECURE_SETTINGS_WHITELIST.add(Settings.Secure.SKIP_FIRST_USE_HINTS);

        SECURE_SETTINGS_DEVICEOWNER_WHITELIST = new HashSet();
        SECURE_SETTINGS_DEVICEOWNER_WHITELIST.addAll(SECURE_SETTINGS_WHITELIST);
        SECURE_SETTINGS_DEVICEOWNER_WHITELIST.add(Settings.Secure.LOCATION_MODE);

        GLOBAL_SETTINGS_WHITELIST = new HashSet();
```

API 22
```java
    static {
        SECURE_SETTINGS_WHITELIST = new HashSet();
        SECURE_SETTINGS_WHITELIST.add(Settings.Secure.DEFAULT_INPUT_METHOD);
        SECURE_SETTINGS_WHITELIST.add(Settings.Secure.SKIP_FIRST_USE_HINTS);
        SECURE_SETTINGS_WHITELIST.add(Settings.Secure.INSTALL_NON_MARKET_APPS);

        SECURE_SETTINGS_DEVICEOWNER_WHITELIST = new HashSet();
        SECURE_SETTINGS_DEVICEOWNER_WHITELIST.addAll(SECURE_SETTINGS_WHITELIST);
        SECURE_SETTINGS_DEVICEOWNER_WHITELIST.add(Settings.Secure.LOCATION_MODE);

        GLOBAL_SETTINGS_WHITELIST = new HashSet();
```

I don't know how to install apks which from unknown source in managed-profile on API 21, if you know that, please give me a solution, thank you.

**Comment by ming030890** [comment]
Thanks for reporting and we will update the documentation.
And I am afraid that there is no workaround for this.

Moreover, I want to point out that enabling unknown source is a bad practice in term of security.
Please consider [Google Play for Work](https://developer.android.com/distribute/googleplay/work/about.html)  to deploy apps in managed profile.

Thanks

**Comment by shizhx** [comment]
@ming030890 I know that enabling unknown source is a bad practice, but you know, not all countries can use Google Play for Work, eg. China

**Comment by ming030890** [comment]
I realize your pain, but I am afraid we can't do much in our side.
Going to close this issue.

Thanks
