### ISSUE TITLE
Disabling home button using android hacks

### ISSUE THREAD

**Issue by suadalshammri** [googlesamples/android-testdpc#61]
I am trying to create an app that disables the home button using android hacks https://github.com/smargav/android-hacks/wiki/Android-Hacks
I found a link, I followed it but I got errors.I added WRITE SETTINGS and WRITE SECURE SETTINGS permissions in the Manifest file and I have a rooted device but its not working.

This is the mainActivity:
    
public class MainActivity extends AppCompatActivity {
    public static final String DEVICE_PROVISIONED = Settings.Global.DEVICE_PROVISIONED;
    public static final String USER_SETUP_COMPLETE = "user_setup_complete";

    @Override
    protected void onCreate(Bundle icicle) {
       // super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        super.onCreate(icicle);

        DevicePolicyManager policyManager = (DevicePolicyManager) getSystemService(Context.DEVICE_POLICY_SERVICE);
       //policyManager.setDeviceOwner("com.suad.myapplication", "MyApplication");

        // Add a persistent setting to allow other apps to know the device has been provisioned.
        Settings.Global.putInt(getContentResolver(), Settings.Global.DEVICE_PROVISIONED, 1);
        Settings.Secure.putInt(getContentResolver(),USER_SETUP_COMPLETE, 1);
       /* try {
            Process process = Runtime.getRuntime().exec(new String[] { "su", "-c", USER_SETUP_COMPLETE});
        } catch (IOException e) {
            e.printStackTrace();
        }*/

        // remove this activity from the package manager.
        PackageManager pm = getPackageManager();
        ComponentName name = new ComponentName(this, MainActivity.class);
        pm.setComponentEnabledSetting(name, PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                PackageManager.DONT_KILL_APP);

        // terminate the activity.
        finish();
    }
}

**Comment by apcsb** [comment]
Touching device_provisioned or user_setup_complete is about the worst thing
you could do - these two disable IMMENSE amount of features and
functionality all over the place - search the source code for them yourself.

Android P offers new lockdown features for the DO DPC to control the user
UI, on older versions you may have to write a custom launcher, so pressing
Home can be controlled by your app.

Writing from the phone, can't provide more details...

**Comment by thechampanurag** [comment]
@suadalshammri @apcsb is there any way to disable powerbutton in kiosk mode using dpc ?
