### ISSUE TITLE
Mainland China cannot access Google's official website. How can I activate device owner？

### ISSUE THREAD

**Issue by wustwg** [googlesamples/android-testdpc#63]
Mainland China cannot access Google's official website. How can I activate device owner？I have tried your sample , the pix just stuck on "正在设置工作设备" 。
Adb setting is still available,but  it's cumbersome if I want to deploy thousands mobile phones.
Google provide various method to active device owner，but I don't know whick is ok if I can't access to google.com.

**Comment by lynnye** [comment]
I don't think we can activate DO using TestDPC alone. Are you talking about setting up work profile? We don't need access to google.com to set up work profile. 

Could you please provide a bug report or video record if you have further questions?

**Comment by legoming** [comment]
For the testdpc, I think it doesn't need access google.com;  the only block is you may unable to download the testdpc apk itself.

One alternative method is using nfc provisioning, you can upload testdpc apk to somewhere can access, then overwrite android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION in nfcprovisioning.txt.
