### ISSUE TITLE
Device Owner is not set while enabling Managed Profile 

### ISSUE THREAD

**Issue by dj-4war** [googlesamples/android-testdpc#73]
I am getting Please contact device administrator while setting up the device owner other words after dpc#identifer on initial provision I am getting this. Here is the my code snippet 

val intent = Intent(DevicePolicyManager.ACTION_PROVISION_MANAGED_DEVICE)
            intent.putExtra(EXTRA_PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME, WeGuardAdminReceiver.getComponentName())
            intent.putExtra(DevicePolicyManager.EXTRA_PROVISIONING_SKIP_ENCRYPTION, true)

            val adminExtras = PersistableBundle()
            //adminExtras.putString("CUSTOME_EXTRAS", "{ \"isCustomExtra\" : true\"}")
            maybeSpecifySyncAuthExtras(intent, adminExtras, actContext)
            maybePassAffiliationIds(intent, adminExtras, actContext)
            if (adminExtras.size() > 0) {
                intent.putExtra(EXTRA_PROVISIONING_ADMIN_EXTRAS_BUNDLE, adminExtras)
            }
            specifyDefaultDisclaimers(intent, actContext)

            if (BuildCompat.isAtLeastN()) {
                specifyColor(intent, actContext)
                specifyLogoUri(intent, actContext)
            }

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                intent.putExtra(EXTRA_PROVISIONING_SKIP_USER_CONSENT,
                        true)
            }

            if (intent.resolveActivity(actContext.getPackageManager()) != null) {
                actContext.startActivityForResult(intent, WeGuardConstants.REQUEST_PROVISION_DEVICE_OWNER)
            } else {
                Toast.makeText(actContext, "DO is only allowed at the time of provision", Toast.LENGTH_SHORT).show()
            }

What could be the issue ?

**Comment by jscott1989** [comment]
Is this a TestDPC issue? If so please demonstrate it using unmodified TestDPC and open a new bug
