### ISSUE TITLE
I can NOT find TYPE_PAUSE in SystemUpdatePolicy

### ISSUE THREAD

**Issue by sungyong2010** [googlesamples/android-testdpc#74]
Hi,
Regarding the TYPE_PAUSE in SystemUpdatePolicy from the Android P here : 
http://androidxref.com/9.0.0_r3/xref/frameworks/base/api/system-current.txt#472
public final class SystemUpdatePolicy implements android.os.Parcelable {
	method public int describeContents();
	method public android.app.admin.SystemUpdatePolicy.InstallationOption getInstallationOptionAt(long);
	method public void writeToParcel(android.os.Parcel, int);
	field public static final android.os.Parcelable.Creator<android.app.admin.SystemUpdatePolicy> CREATOR;
	field public static final int TYPE_PAUSE = 4; // 0x4
}

But I can NOT find related TYPE_PAUSE in this Test DPC.
Also I can NOT find TYPE_PAUSE below URL.
https://developer.android.com/reference/android/app/admin/SystemUpdatePolicy

I was wondering if you could you help me out.
Thanks.

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
