### ISSUE TITLE
Apps in Work Profile crash after Reboot Including TestDPC

### ISSUE THREAD

**Issue by sriram-kakarala** [googlesamples/android-testdpc#75]
**Issue:** After creating Work Profile using TestDPC and restarting the device, all the Work Profile apps crash/not able to be launched. The TestDPC application crashes.

**Device:** HMD Global Nokia 6.1
**OS:** 9.0
**Frequency** - Always
**Workaround** - If we disable the work-profile and then re-enable it then everything works until the next reboot.

**Logs** - PFA[](url)
[adb_logs_during_setup.txt](https://github.com/googlesamples/android-testdpc/files/2659650/adb_logs_during_setup.txt)
[adb_logs_post_reboot.txt](https://github.com/googlesamples/android-testdpc/files/2659651/adb_logs_post_reboot.txt)

**Comment by jscott1989** [comment]
Are you able to reproduce this bug when creating a Work Profile with any other DPC? otherwise it looks like a general work profile bug rather than a TestDPC bug.

Feel free to re-open this bug if you find it's only reproducible when using TestDPC.
