### ISSUE TITLE
Device owner provisioning on device with QR Code method Failed

### ISSUE THREAD

**Issue by mnadeem9** [googlesamples/android-testdpc#76]
If the package name i.e com.afwsamples.testdpc is renamed to something else i.e. com.xxxxx.yyyy for Android-testdpc application then none of the DeviceAdminReceiver methods like onEnable , onProfileProvisioningComplete are invoked. The application is installed and provisioning is complete successfully but methods are not invoked to perform post Provisioning task. 
Note : If I dont change the package then its works fine as expected. This happens on ASUS Zenpad tab with Android OS 7.0. I have confirmed this after trying more than 80 time. Any Suggestions why this restriction ?

**Comment by jscott1989** [comment]
My assumption would be that this was caused by a mismatch between your provisioning parameters (from QR code etc.) and the DPC application. There should be no restriction on package name in general.
