### ISSUE TITLE
Random background crash when resuming TestDPC.

### ISSUE THREAD

**Issue by raghi9** [googlesamples/android-testdpc#79]
as per logs :

12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime: FATAL EXCEPTION: main
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 8368
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x1 (unknown) for fragment LockScreenPolicyFragment{566d833 #0 id=0x1 profile}
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1292)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3050)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3002)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.Fragment.performActivityCreated(Fragment.java:2537)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2430)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2209)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2165)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2066)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:873)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:214)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7023)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-27 09:33:53.272 1010187  8368  8368 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by abhisheksubal** [comment]
This issue is reproduced when pressing up Button in Action Bar in PolicySearchFragment after opening it from LockScreenPolicyFragment and PasswordConstraintsFragment.
