### ISSUE TITLE
Settings app crashes while removing device owner.

### ISSUE THREAD

**Issue by amalChandran** [googlesamples/android-testdpc#8]
Steps to reproduce:

1. Enable an App1 as device owner. Setup kiosk by making one of the activity as home launcher. 
2. Start lock task on ActivityA.
3. Stop lock task on a different activity(Accidentally).
 Do step three multiple times. 

 Trying to uninstll App1 will take us to Device Administration Settings page. Unticking App1 as device owner crashes the Settings app.

Now the App1 can never be unistalled.

Device used: Moto g2 (Android M)

![device-2016-06-28-165053](https://cloud.githubusercontent.com/assets/4386056/16413608/88e82bca-3d50-11e6-864c-83b1e6e5df04.png)

**Comment by ming030890** [comment]
Is App1 TestDPC?
Could you attach the crash log here?
Thanks

**Comment by ming030890** [comment]
And some more questions :)

What do you mean "Stop lock task on a different activity"?
And how do you uninstall "App1" if you are in lock task mode? Also, from my understanding, you should not be able to unisntall/ deactivate DO in system settings.

Thanks

**Comment by amalChandran** [comment]
App1 is a demo app I made. I do not have the crashlogs now. Will try to reproduce it and update shortly.

App1 has multiple activities, While I locked Activity1, I called stop lock on Activity2.

You are correct that we cannot remove device owner from settings. I first called clearDeviceOwnerApp from the App1. Then went to Admin page to untick App1 as the device owner. This is when the Settings app crashed.

**Comment by ming030890** [comment]
Device administrators is different from device owner, and calling clearDeviceOwnerApp should remove both DO and Device administrators status of your app, no UI interaction should be needed. You can try the clear device owner option in TestDPC.

I am going to close the issue and please reopen it if you can reproduce and capture the related log.

Thanks!

**Comment by amalChandran** [comment]
"calling clearDeviceOwnerApp should remove both DO and Device administrators status of your app no UI interaction should be needed"

Well this is not true. Here is a video of uninstalling the TestDPC app. https://drive.google.com/file/d/0B4Sf9EwVaZ6jZ3EwVkVDcllDYVE/view?usp=sharing

Ill reopen this if I am able to reproduce the crash.

**Comment by ming030890** [comment]
Fail to reproduce it in android N, it should be fixed.
