### ISSUE TITLE
Import Certs in EAP-TLS Wi-Fi configuration

### ISSUE THREAD

**Issue by wallace000** [googlesamples/android-testdpc#84]
Anyone know why I can't import CA certificates using DPC when creating an EAP-TLS Wi-Fi configuration?
I've tried .cer .pfx etc and all are greyed out for selection. Doesn't look possible

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
