### ISSUE TITLE
Values from 10th Bundle in a Bundle Array end up getting saved in the  2nd bundle.

### ISSUE THREAD

**Issue by theDarkerHorse** [googlesamples/android-testdpc#86]
Using Bundle Array as explained here : https://developer.android.com/work/managed-configurations. 

Values save correctly from the 0th Bundle to the 9th bundle without any issues . 
However , the value saved in the 10th bundle gets saved in the 2nd bundle thus overriding the second bundle . 

Is this a known issue , or is it expected behavior ?

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
