### ISSUE TITLE
Test DPC thinks app is not installed

### ISSUE THREAD

**Issue by sisterray** [googlesamples/android-testdpc#87]
My app is a xamarin app. I am trying to test app restrictions

When i install my app by building and deploying from visual studio, as expected i get a two versions, one launch icon with a test dpc badge and one without.

When i install the app by downloading the apk and installing it manually, the app launch icon does not have the test dpc badge.

It does not appear in the apps that can have their app restrictions. In the section where the list of managed apps is shown my app is not listed

I tried adding my app by entering the application id but test dpc crashed because it said my app was not installed

How do I add my app into test dpc when the apk is manually installed on the device?

**Comment by theDarkerHorse** [comment]
Interesting , I do not have that issue . Are you installing an apk after downloading from a link or using "adb install -r   package_name.apk ?

**Comment by sisterray** [comment]
When I downloaded the app then installed it on the device, there is only an unmanaged version installed. However I found that when I install from my computer via adb install it shows the unmanaged and managed version. So this issue can be closed.
