### ISSUE TITLE
Crash in test DPC when resetting password

### ISSUE THREAD

**Issue by RobinAhuja** [googlesamples/android-testdpc#88]
Create DO using QR code
a) DPC > Reset Password
b) 'Set New Token' > tap 'Activate'
c) Input new password with 3 letters > tap 'SET PASSWORD'

--------- beginning of crash
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime: FATAL EXCEPTION: main
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 22022
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%s'
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at java.util.Formatter.format(Formatter.java:2522)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at java.util.Formatter.format(Formatter.java:2458)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at java.lang.String.format(String.java:2883)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at android.content.res.Resources.getString(Resources.java:481)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at android.app.Fragment.getString(Fragment.java:803)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at com.afwsamples.testdpc.policy.PolicyManagementFragment.showToast(PolicyManagementFragment.java:2823)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at com.afwsamples.testdpc.policy.PolicyManagementFragment.access$100(PolicyManagementFragment.java:223)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at com.afwsamples.testdpc.policy.PolicyManagementFragment$19.onClick(PolicyManagementFragment.java:2116)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:214)
05-22 15:34:43.994 1010166 22022 22022 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7159)

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
