### ISSUE TITLE
Crash when setting up profile on Nexus 5X running Marshmallow

### ISSUE THREAD

**Issue by bjvetter** [googlesamples/android-testdpc#9]
I downloaded and built the Test DPC with no changes (using the N SDK on Android Studio). After it starts creating the profile, I see it switch back to the home page and it puts up an error stating that Test DPC has stopped. In the logcat output, I see a fatal exception being thrown - it can't find the android.support.v4.content.FileProvider class.

Installing and running Test DPC from the Play Store on the same device seems to work just fine. Is there a specific version of Android Studio and the SDK required besides Android N alpha2?

**Comment by ming030890** [comment]
The class is in support library,  please make sure you have downloaded
the *Android
Support* library using the SDK Manager
<https://developer.android.com/topic/libraries/support-library/setup.html#download>
.
Also worth try a clean build.

Thanks

**Comment by bjvetter** [comment]
I have the support library, did a clean build, updated the SDK and the SDK tools, and still get the error when running the built app. The problem is not at compile time - the problem doesn't show up until run time.

That said, I removed everything from my device, reset my gradle version from 2.1.2 to 2.1.0 and then did another clean build, and it worked. Not sure if gradle 2.1.2  produced the issue or if something else is going on.
