### ISSUE TITLE
Generate a private/public key pair / FAILED key generation

### ISSUE THREAD

**Issue by guliverx** [googlesamples/android-testdpc#90]
the Generation of a private / public Key failed with:

FAILED key generation

I want only to create a certifacte with IMEI .. 

When i debugged the app i have here the problem:

           final boolean success = mService.generateKeyPair(
                    admin, mContext.getPackageName(), algorithm, parcelableSpec,
                    idAttestationFlags, attestationChain);
            if (!success) {
                Log.e(TAG, "Error generating key via DevicePolicyManagerService.");
                return null;
            }

generateKeyPair failed using mService !!

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
