### ISSUE TITLE
Harcoded Top Margin system_update_policy.xml

### ISSUE THREAD

**Issue by abhisheksubal** [googlesamples/android-testdpc#91]
The top margin for the Set new policy button is fixed at 48dip which results in button drifting down in devices with small screen, and the user cannot see the button.
`<Button android:id="@+id/system_update_policy_set"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/system_update_policy_windowed_details"
        android:layout_alignParentLeft="true"
        android:layout_marginTop="48dip"
        android:text="@string/system_update_policy_set_policy" />`

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
