### ISSUE TITLE
test-dpc-5-0-4

### ISSUE THREAD

**Issue by DarthMoulByte** [googlesamples/android-testdpc#92]
Do you recognize this app as your authorship or property? If so, could you tell me where your documentation, repository and compilation manual is?...

y que diferencia hay entre esta apk 
https://doc-0g-80-docs.googleusercontent.com/docs/securesc/alhb0jv0k1dqiedck37986hsioe82apl/7e528dbksn7901bgeb0h78udq99nq1ct/1564005600000/11964503490876937518/17273109689422215523/1xHQYGELQewU5Y8F693PL7TYPRBqoNh2Q?e=download&nonce=ce3f0t4ue0s26&user=17273109689422215523&hash=0u432eud8jh1iupactgnbpsnvtm2qmjk
link reference video
[https://www.youtube.com/watch?v=sZ7n0TE3VGU](url)

completely ignores if it can contain malicious code, and because there are differences such as that when installed it is blocked to be removed, which does not allow it to be deleted once installed, what took me to this place is that on a page they show images of your app and has the same appearance and appearance in general, unless I ignore its origin, my doubts also arise that many people promote it in videos of hacks for android, when doing field research I arrived here but I do not see the connection clearly

**Comment by jscott1989** [comment]
I can't see the doc you linked.

This is the respository for Test DPC. Test DPC is an app designed to help EMMs, ISVs, and OEMs to test their applications and platforms in a Android enterprise managed profile (i.e. work profile). It serves as both a sample Device Policy Controller and a testing application to flex the APIs available for Android enterprise. It supports devices running Android 5.0 Lollipop or later.

See the documentation to learn more about Android in the enterprise.

You should either compile this yourself or use https://play.google.com/store/apps/details?id=com.afwsamples.testdpc from the Play Store.
