### ISSUE TITLE
How to make delegated cert installer option work?

### ISSUE THREAD

**Issue by psmorandi** [googlesamples/android-testdpc#95]
Hello,

I'm trying to delegate install certs to an app that we have. I could not make it work. I have some questions that maybe would help me sort this out. I'm trying to call [uninstallAllUserCaCerts](https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#uninstallAllUserCaCerts(android.content.ComponentName)) just as a test. And I'm receiving in log cat:

> E/MainActivity: java.lang.SecurityException: Admin ComponentInfo{br.com.mobiltec.c4m.android.agent/br.com.mobiltec.c4m.android.library.deviceadmin.DeviceAdminReceiver} does not own the profile

Questions:

1. What should I pass as **android.content.ComponentName**? My app is "device admin" and I "delegated" install certs with the Test DPC. The class/package in the error above is what I'm currently passing to [uninstallAllUserCaCerts](https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#uninstallAllUserCaCerts(android.content.ComponentName)).
2. Am I missing any other call to [DevicePolicyManager](https://developer.android.com/reference/android/app/admin/DevicePolicyManager) to "prepare" for this? I guess this delegation should be straight forward. Just give and you're done.
3. Do I need any permissions in my manifest for this "delegation"? It's not clear in docs that I need any kind of extra permission.

**Comment by psmorandi** [comment]
So, after a while I found a solution. The problem is that to use as a delegated scope you must pass null to ComponentName.

```
DevicePolicyManager d = (DevicePolicyManager) 				                                                      this.getSystemService(Context.DEVICE_POLICY_SERVICE);
d.installCaCert(null, cert);
```
Hope that this help others.

**Comment by MrChenYiFei** [comment]
Thank you so much
