### ISSUE TITLE
Any way to use this with Android Management API?

### ISSUE THREAD

**Issue by guikubivan** [googlesamples/android-testdpc#96]
I apologize is this is the wrong place to post this question in advance. Open to recommendations to other forums where this question is better fitted.

We have a use case where the Android Management API meets almost all of our needs. 
However, we need to specify an app that we're shipping with our MDM solution to always be running and have access to location polling (background is fine), i.e., app should be exempted from force stopping by the OS. The Android Management API doesn't seem to allow for an app to be privileged in any way.

**Comment by guikubivan** [comment]
Edit: Updated the text in the question.

**Comment by jscott1989** [comment]
TestDPC is just a standalone DPC used for testing APIs and won't integrate with Android Management API.

To ask questions of Android Management API see https://developers.google.com/android/management/feedback
