### ISSUE TITLE
WifiConfigUtil.saveWifiConfiguration is broken - impossible to create a Wifi profile

### ISSUE THREAD

**Issue by fabiosmirmaul** [googlesamples/android-testdpc#97]
Although WifiManager.saveConfiguration() is deprecated from since API 26, it used to return "true" until Android P.
However, from Android Q, Google has changed it to return "false".

It has broken the DPC API to create a Wifi Profile since it relies on the returning of WifiManager.saveConfiguration, as below:

`        // Added successfully, try to save it now. `
`        wifiManager.enableNetwork(networkId, /* disableOthers */ false); `
`        if (wifiManager.saveConfiguration()) { `
`            return true;`
`        } else {`
`            // Remove the added network that fail to save.`
`            wifiManager.removeNetwork(networkId);`
`            return false;`
`        }` 

Suggestion:
     Please remove the calling of WifiManager.saveConfiguration. 
     Accordinfg to documentation, it is not needed anymore.
https://developer.android.com/reference/android/net/wifi/WifiManager.html#saveConfiguration()

Thanks

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
