### ISSUE TITLE
QR Provisioning error

### ISSUE THREAD

**Issue by Maurice1V45** [googlesamples/android-testdpc#99]
Hi everyone,

I'm trying to provision a device after factory reset by scanning a QR code. If I scan the QR code here http://down-box.appspot.com/qr/nQB0tw7b it downloads the dpc test app and everything goes smoothly.

But if I download the project, import it into Android Studio, build a signed apk, upload it to a website, generate a QR code and then scan it, it downloads the app and then shows me this error:
Can't set up device
Can't use the admin app. It's missing components or corrupted. For help, contact your admin.

I haven't modified anything in the project, it's exactly as it is on the GitHub page. My QR code looks like this:
{
	"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.afwsamples.testdpc/com.afwsamples.testdpc.DeviceAdminReceiver",
	"android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "qUp3dzilorOcBGSoszNUy57oJRX8nWKNcgQKfRnONzs",
	"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "http://www.droidbin.com/mylinktoapk"
}

I don't receive the checksum error, instead I think It has to do something with the DeviceAdminReceiver, because the error I receive is the same as the error I get when I input an incorrect PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME.
What am I missing here?

**Comment by Maurice1V45** [comment]
I found the issue. It's related to "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "http://www.droidbin.com/mylinktoapk"
Even though I provided a direct download link, it seems android wasn't able to download the apk from the given link (reasons still unknown). So after trying a couple of free file hosting services, I found one that allows the apk to be downloaded and installed after scanning the QR code.

**Comment by Maurice1V45** [comment]
The file hosting service that I used back then which made the provisioning work was https://filetransfer.io/
I hope this helps someone.

**Comment by rudraumapp** [comment]
> Hi everyone,
> 
> I'm trying to provision a device after factory reset by scanning a QR code. If I scan the QR code here http://down-box.appspot.com/qr/nQB0tw7b it downloads the dpc test app and everything goes smoothly.
> 
> But if I download the project, import it into Android Studio, build a signed apk, upload it to a website, generate a QR code and then scan it, it downloads the app and then shows me this error: Can't set up device Can't use the admin app. It's missing components or corrupted. For help, contact your admin.
> 
> I haven't modified anything in the project, it's exactly as it is on the GitHub page. My QR code looks like this: { "android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.afwsamples.testdpc/com.afwsamples.testdpc.DeviceAdminReceiver", "android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "qUp3dzilorOcBGSoszNUy57oJRX8nWKNcgQKfRnONzs", "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "http://www.droidbin.com/mylinktoapk" }
> 
> I don't receive the checksum error, instead I think It has to do something with the DeviceAdminReceiver, because the error I receive is the same as the error I get when I input an incorrect PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME. What am I missing here?

PLEASE HELP!!!
Can you tell me how did you have generated checksum???

**Comment by kirkaDev** [comment]
> 

Hello, rudraumapp. 
I use Windows for work and I didn't find any info on how to get checksum, but I asked my friend to run the command on Linux. 
It looks like this:
`apksigner verify -print-certs my.apk | perl -nle 'print $& if m{(?<=SHA-256 digest:) .*}'  | xxd -r -p | openssl base64 | tr -d '=' | tr -- '+/=' '-_'
`
And I got this result:
JYhj9Cwf0YnDHl21XVnqCSOgZ4qOQHc0wC2-AMCGCXw

I struggled with this for a long time.
There were problems with checksum, as well as with remote access to the file for downloading the apk file. 
As a result, I bought some kind of free hosting, gave the necessary rights to the directory and file, and everything worked out..

**Comment by rudraumapp** [comment]
I did this but it's shows "Can't set up device  Contact your IT admin for help"
 
{"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.rudraum.testdpc/com.rudraum.testdpc.DeviceAdminReceiver",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "sY/16btnQhZyIYbvBm4obpRSlw4gtjRDFWXri0NxmKw=",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION":"http://rudraum.com/rudraumdcp_release.apk",
"android.app.extra.PROVISIONING_LEAVE_ALL_SYSTEM_APPS_ENABLED":true,
"android.app.extra.PROVISIONING_SKIP_ENCRYPTION":false}

**Comment by kirkaDev** [comment]
> I did this but it's shows "Can't set up device Contact your IT admin for help"
> 
> {"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.rudraum.testdpc/com.rudraum.testdpc.DeviceAdminReceiver", "android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "sY/16btnQhZyIYbvBm4obpRSlw4gtjRDFWXri0NxmKw=", "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION":"http://rudraum.com/rudraumdcp_release.apk", "android.app.extra.PROVISIONING_LEAVE_ALL_SYSTEM_APPS_ENABLED":true, "android.app.extra.PROVISIONING_SKIP_ENCRYPTION":false}

Maybe the problem is that you are using http (not https)?

Here is template created from my working example:
```
{
"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME":
"ru.my.company/.DeviceAdmin",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM":
"JYhj9Cwf0YnDHl21XVnqCSOgZ4qOQHc0wC2-AMCGCXw",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION":
"https://xxxxx.tmweb.ru/folder/app_full_functionality.apk",
"android.app.extra.PROVISIONING_SKIP_ENCRYPTION": false,
"android.app.extra.PROVISIONING_WIFI_SSID": "your_wifi_name",
"android.app.extra.PROVISIONING_WIFI_PASSWORD": "your_wifi_password",
"android.app.extra.PROVISIONING_WIFI_SECURITY_TYPE": "your Wi-Fi security type",
"android.app.extra.PROVISIONING_ADMIN_EXTRAS_BUNDLE": {
}
}
```

**Comment by rudraumapp** [comment]
Same checksum error

**Comment by rostik404** [comment]
I had the same problem as topic starter, and I found the mistake in my QR code.
My device admin component path looked like:
`"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME":
"my.cool.app/.DeviceAdmin"` and it worked in most Android versions, but in Android 8 I had an error: `Can't use the admin app. It's missing components or corrupted`.

I changed a relative path to absolute path like this:
`"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME":
"my.cool.app/my.cool.app.DeviceAdmin"` and it helped.

Maybe it'll be helpful for somebody :)

**Comment by iMoregano007** [comment]
hello everyone, 
i'm facing the issue in QR provisioning something similar to the OP Guy, 
when i use the debug apk for provisioning i get the error message could not use the admin app due to checksum error, contact your IT admin, 
i tried the online solution i found which suggested to use signed apk instead which will resolve the error but when i tried to do with the signed apk, now i'm getting the error could not complete the setup because the admin app is missing component or corrupted, contact your IT admin , 
the json payload i'm using is 
{
  "android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.alobha.sample.myapplication/com.alobha.sample.myapplication.AdminReceiver",
  "android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "0F935A953B2D6708B3B15DD70DF778DF550012A56978E17EBB91DF3B1C66349F",
  "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "https://alobhaitsolution.com/app-release-aligned.apk"
}

if any one could help it will be much useful , ( i have tried all the previous suggestions)
Thanks

**Comment by iravikant** [comment]
Hello 
i have  use either google test DPC app or My own signed build app for qr code provisioning 
i got every time same error "Something went wrong please contact your admin       or      Couldn`t Setup device "

this is my Json format for qr code generation
```
**{
  "android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.my app/.myAdminReceiver",
  "android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "7yRxgSgepvItKzc+eDZi3qaIdVlzKwyM27+mujSVU0U",
  "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "https://android-application/test/app-release.apk",
  "android.app.extra.PROVISIONING_LEAVE_ALL_SYSTEM_APPS_ENABLED": true,
  "android.app.extra.PROVISIONING_SKIP_ENCRYPTION": false
}**
```

my conditions 
using this JSON format to generate qr code >> provision device by 6 time tapping on new fresh android device >> Downloading app >> got a screen where i got a message  This device belongs to Your Organization >>> after that got error screen ( "Something went wrong please contact your admin  or      Couldn`t Setup device ")

please help me

**Comment by YashVaghasiya2710** [comment]
@

> Hello i have use either google test DPC app or My own signed build app for qr code provisioning i got every time same error "Something went wrong please contact your admin or Couldn`t Setup device "
> 
> this is my Json format for qr code generation
> 
> ```
> **{
>   "android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME": "com.my app/.myAdminReceiver",
>   "android.app.extra.PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM": "7yRxgSgepvItKzc+eDZi3qaIdVlzKwyM27+mujSVU0U",
>   "android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION": "https://android-application/test/app-release.apk",
>   "android.app.extra.PROVISIONING_LEAVE_ALL_SYSTEM_APPS_ENABLED": true,
>   "android.app.extra.PROVISIONING_SKIP_ENCRYPTION": false
> }**
> ```
> 
> my conditions using this JSON format to generate qr code >> provision device by 6 time tapping on new fresh android device >> Downloading app >> got a screen where i got a message This device belongs to Your Organization >>> after that got error screen ( "Something went wrong please contact your admin or Couldn`t Setup device ")
> 
> please help me

have yo found solution

**Comment by longquangpham90** [comment]
We have the same issue with Samsung S10 FE+ 
But the tablet Lenovo we can scan and install with QR Code Provisioning
